Name     : apache-hadoop
Version  : 2.7.3
Release  : 7
URL      : http://apache.cs.utah.edu/hadoop/common/hadoop-2.7.3/hadoop-2.7.3-src.tar.gz
Source0  : http://apache.cs.utah.edu/hadoop/common/hadoop-2.7.3/hadoop-2.7.3-src.tar.gz
Source1  : http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.44/bin/apache-tomcat-6.0.44.tar.gz
Source2  : hadoop-layout.sh
Source3  : https://repo.maven.apache.org/maven2/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
BuildRequires : hadoop-dep
BuildRequires : openjdk-dev
BuildRequires : protobuf
Buildrequires : apache-maven
BuildRequires : cmake
BuildRequires : zlib-dev
BuildRequires : openssl-dev
Patch0   : 0001-Change-protobuf-version.patch
Patch1   : protobuf3.patch
Patch2   : 0001-Java_home-on-CLR.patch

%description

%prep
%setup -q -n hadoop-2.7.3-src
%patch0 -p1 
%patch1 -p1
%patch2 -p1

%build
mkdir -p %{buildroot}
cp -r /usr/share/apache-hadoop/.m2 %{buildroot}/.m2

# Copy apache-tomcat
mkdir hadoop-common-project/hadoop-kms/downloads
mkdir hadoop-hdfs-project/hadoop-hdfs-httpfs/downloads
cp %{SOURCE1} hadoop-common-project/hadoop-kms/downloads
cp %{SOURCE1} hadoop-hdfs-project/hadoop-hdfs-httpfs/downloads

# Build Hadoop
# TODO compile Hadoop with -Pdocs, but fails
mvn package -o -Pnative -Pdist -DskipTests -Dtar \
-Dmaven.repo.local=%{buildroot}/.m2/repository

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr
tar -xf hadoop-dist/target/hadoop-2.7.3.tar.gz -C %{buildroot}/usr --strip-components=1
mv %{buildroot}/usr/*.txt %{buildroot}/usr/share/doc/hadoop
mv %{buildroot}/usr/etc %{buildroot}/usr/share/hadoop/etc

# Install hadoop-layout.sh
cp %{SOURCE2} %{buildroot}/usr/libexec/hadoop-layout.sh

# Fix java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup
cp %{SOURCE3} %{buildroot}/usr/share/hadoop/common/lib/

%files
%defattr(-,root,root,-)
/usr/bin/container-executor
/usr/bin/hadoop
/usr/bin/hadoop.cmd
/usr/bin/hdfs
/usr/bin/hdfs.cmd
/usr/bin/mapred
/usr/bin/mapred.cmd
/usr/bin/rcc  
/usr/bin/test-container-executor
/usr/bin/yarn
/usr/bin/yarn.cmd
/usr/include/Pipes.hh
/usr/include/SerialUtils.hh
/usr/include/StringUtils.hh
/usr/include/TemplateFactory.hh
/usr/include/hdfs.h
/usr/lib/native/libhadoop.a
/usr/lib/native/libhadoop.so
/usr/lib/native/libhadoop.so.1.0.0
/usr/lib/native/libhadooppipes.a
/usr/lib/native/libhadooputils.a
/usr/lib/native/libhdfs.a
/usr/lib/native/libhdfs.so
/usr/lib/native/libhdfs.so.0.0.0
/usr/libexec/hadoop-config.cmd
/usr/libexec/hadoop-config.sh
/usr/libexec/hadoop-layout.sh
/usr/libexec/hdfs-config.cmd
/usr/libexec/hdfs-config.sh
/usr/libexec/httpfs-config.sh
/usr/libexec/kms-config.sh
/usr/libexec/mapred-config.cmd
/usr/libexec/mapred-config.sh
/usr/libexec/yarn-config.cmd
/usr/libexec/yarn-config.sh
/usr/sbin/distribute-exclude.sh
/usr/sbin/hadoop-daemon.sh
/usr/sbin/hadoop-daemons.sh
/usr/sbin/hdfs-config.cmd
/usr/sbin/hdfs-config.sh
/usr/sbin/httpfs.sh
/usr/sbin/kms.sh
/usr/sbin/mr-jobhistory-daemon.sh
/usr/sbin/refresh-namenodes.sh
/usr/sbin/slaves.sh
/usr/sbin/start-all.cmd
/usr/sbin/start-all.sh
/usr/sbin/start-balancer.sh
/usr/sbin/start-dfs.cmd
/usr/sbin/start-dfs.sh
/usr/sbin/start-secure-dns.sh
/usr/sbin/start-yarn.cmd
/usr/sbin/start-yarn.sh
/usr/sbin/stop-all.cmd
/usr/sbin/stop-all.sh
/usr/sbin/stop-balancer.sh
/usr/sbin/stop-dfs.cmd
/usr/sbin/stop-dfs.sh
/usr/sbin/stop-secure-dns.sh
/usr/sbin/stop-yarn.cmd
/usr/sbin/stop-yarn.sh
/usr/sbin/yarn-daemon.sh
/usr/sbin/yarn-daemons.sh
/usr/share/doc/hadoop/LICENSE.txt
/usr/share/doc/hadoop/NOTICE.txt
/usr/share/doc/hadoop/README.txt
/usr/share/doc/hadoop/common/CHANGES.txt
/usr/share/doc/hadoop/hdfs/CHANGES.txt
/usr/share/doc/hadoop/mapreduce/CHANGES.txt
/usr/share/doc/hadoop/yarn/CHANGES.txt
/usr/share/hadoop/common/hadoop-common-2.7.3-tests.jar
/usr/share/hadoop/common/hadoop-common-2.7.3.jar
/usr/share/hadoop/common/hadoop-nfs-2.7.3.jar
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.6.0.xml
/usr/share/hadoop/common/jdiff/Null.java
/usr/share/hadoop/common/jdiff/hadoop-core_0.20.0.xml
/usr/share/hadoop/common/jdiff/hadoop-core_0.21.0.xml
/usr/share/hadoop/common/jdiff/hadoop-core_0.22.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.17.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.2.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.3.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.2.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.2.xml
/usr/share/hadoop/common/lib/activation-1.1.jar
/usr/share/hadoop/common/lib/apacheds-i18n-2.0.0-M15.jar
/usr/share/hadoop/common/lib/apacheds-kerberos-codec-2.0.0-M15.jar
/usr/share/hadoop/common/lib/api-asn1-api-1.0.0-M20.jar
/usr/share/hadoop/common/lib/api-util-1.0.0-M20.jar
/usr/share/hadoop/common/lib/asm-3.2.jar
/usr/share/hadoop/common/lib/avro-1.7.4.jar
/usr/share/hadoop/common/lib/commons-beanutils-1.7.0.jar
/usr/share/hadoop/common/lib/commons-beanutils-core-1.8.0.jar
/usr/share/hadoop/common/lib/commons-cli-1.2.jar
/usr/share/hadoop/common/lib/commons-codec-1.4.jar
/usr/share/hadoop/common/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/common/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/common/lib/commons-configuration-1.6.jar
/usr/share/hadoop/common/lib/commons-digester-1.8.jar
/usr/share/hadoop/common/lib/commons-httpclient-3.1.jar
/usr/share/hadoop/common/lib/commons-io-2.4.jar
/usr/share/hadoop/common/lib/commons-lang-2.6.jar
/usr/share/hadoop/common/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/common/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/common/lib/commons-net-3.1.jar
/usr/share/hadoop/common/lib/curator-client-2.7.1.jar
/usr/share/hadoop/common/lib/curator-framework-2.7.1.jar
/usr/share/hadoop/common/lib/curator-recipes-2.7.1.jar
/usr/share/hadoop/common/lib/gson-2.2.4.jar
/usr/share/hadoop/common/lib/guava-11.0.2.jar
/usr/share/hadoop/common/lib/hadoop-annotations-2.7.3.jar
/usr/share/hadoop/common/lib/hadoop-auth-2.7.3.jar
/usr/share/hadoop/common/lib/hamcrest-core-1.3.jar
/usr/share/hadoop/common/lib/htrace-core-3.1.0-incubating.jar
/usr/share/hadoop/common/lib/httpclient-4.2.5.jar
/usr/share/hadoop/common/lib/httpcore-4.2.5.jar
/usr/share/hadoop/common/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/common/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/common/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/common/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/common/lib/java-xmlbuilder-0.4.jar
/usr/share/hadoop/common/lib/jaxb-api-2.2.2.jar
/usr/share/hadoop/common/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/common/lib/jersey-core-1.9.jar
/usr/share/hadoop/common/lib/jersey-json-1.9.jar
/usr/share/hadoop/common/lib/jersey-server-1.9.jar
/usr/share/hadoop/common/lib/jets3t-0.9.0.jar
/usr/share/hadoop/common/lib/jettison-1.1.jar
/usr/share/hadoop/common/lib/jetty-6.1.26.jar
/usr/share/hadoop/common/lib/jetty-util-6.1.26.jar
/usr/share/hadoop/common/lib/jsch-0.1.42.jar
/usr/share/hadoop/common/lib/jsp-api-2.1.jar
/usr/share/hadoop/common/lib/jsr305-3.0.0.jar
/usr/share/hadoop/common/lib/junit-4.11.jar
/usr/share/hadoop/common/lib/log4j-1.2.17.jar
/usr/share/hadoop/common/lib/mockito-all-1.8.5.jar
/usr/share/hadoop/common/lib/netty-3.6.2.Final.jar
/usr/share/hadoop/common/lib/netty-all-4.0.23.Final.jar
/usr/share/hadoop/common/lib/paranamer-2.3.jar
/usr/share/hadoop/common/lib/protobuf-java-3.2.0.jar
/usr/share/hadoop/common/lib/servlet-api-2.5.jar
/usr/share/hadoop/common/lib/slf4j-api-1.7.10.jar
/usr/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar
/usr/share/hadoop/common/lib/snappy-java-1.0.4.1.jar
/usr/share/hadoop/common/lib/stax-api-1.0-2.jar
/usr/share/hadoop/common/lib/xmlenc-0.52.jar
/usr/share/hadoop/common/lib/xz-1.0.jar
/usr/share/hadoop/common/lib/zookeeper-3.4.6.jar
/usr/share/hadoop/common/sources/hadoop-common-2.7.3-sources.jar
/usr/share/hadoop/common/sources/hadoop-common-2.7.3-test-sources.jar
/usr/share/hadoop/common/templates/core-site.xml
/usr/share/hadoop/etc/hadoop/capacity-scheduler.xml
/usr/share/hadoop/etc/hadoop/configuration.xsl
/usr/share/hadoop/etc/hadoop/container-executor.cfg
/usr/share/hadoop/etc/hadoop/core-site.xml
/usr/share/hadoop/etc/hadoop/hadoop-env.cmd
/usr/share/hadoop/etc/hadoop/hadoop-env.sh
/usr/share/hadoop/etc/hadoop/hadoop-metrics.properties
/usr/share/hadoop/etc/hadoop/hadoop-metrics2.properties
/usr/share/hadoop/etc/hadoop/hadoop-policy.xml
/usr/share/hadoop/etc/hadoop/hdfs-site.xml
/usr/share/hadoop/etc/hadoop/httpfs-env.sh
/usr/share/hadoop/etc/hadoop/httpfs-log4j.properties
/usr/share/hadoop/etc/hadoop/httpfs-signature.secret
/usr/share/hadoop/etc/hadoop/httpfs-site.xml
/usr/share/hadoop/etc/hadoop/kms-acls.xml
/usr/share/hadoop/etc/hadoop/kms-env.sh
/usr/share/hadoop/etc/hadoop/kms-log4j.properties
/usr/share/hadoop/etc/hadoop/kms-site.xml
/usr/share/hadoop/etc/hadoop/log4j.properties
/usr/share/hadoop/etc/hadoop/mapred-env.cmd
/usr/share/hadoop/etc/hadoop/mapred-env.sh
/usr/share/hadoop/etc/hadoop/mapred-queues.xml.template
/usr/share/hadoop/etc/hadoop/mapred-site.xml.template
/usr/share/hadoop/etc/hadoop/slaves
/usr/share/hadoop/etc/hadoop/ssl-client.xml.example
/usr/share/hadoop/etc/hadoop/ssl-server.xml.example
/usr/share/hadoop/etc/hadoop/yarn-env.cmd
/usr/share/hadoop/etc/hadoop/yarn-env.sh
/usr/share/hadoop/etc/hadoop/yarn-site.xml
/usr/share/hadoop/hdfs/hadoop-hdfs-2.7.3-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-2.7.3.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-nfs-2.7.3.jar
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.6.0.xml
/usr/share/hadoop/hdfs/jdiff/Null.java
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.20.0.xml
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.21.0.xml
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.22.0.xml
/usr/share/hadoop/hdfs/lib/asm-3.2.jar
/usr/share/hadoop/hdfs/lib/commons-cli-1.2.jar
/usr/share/hadoop/hdfs/lib/commons-codec-1.4.jar
/usr/share/hadoop/hdfs/lib/commons-daemon-1.0.13.jar
/usr/share/hadoop/hdfs/lib/commons-io-2.4.jar
/usr/share/hadoop/hdfs/lib/commons-lang-2.6.jar
/usr/share/hadoop/hdfs/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/hdfs/lib/guava-11.0.2.jar
/usr/share/hadoop/hdfs/lib/htrace-core-3.1.0-incubating.jar
/usr/share/hadoop/hdfs/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/hdfs/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/hdfs/lib/jersey-core-1.9.jar
/usr/share/hadoop/hdfs/lib/jersey-server-1.9.jar
/usr/share/hadoop/hdfs/lib/jetty-6.1.26.jar
/usr/share/hadoop/hdfs/lib/jetty-util-6.1.26.jar
/usr/share/hadoop/hdfs/lib/jsr305-3.0.0.jar
/usr/share/hadoop/hdfs/lib/leveldbjni-all-1.8.jar
/usr/share/hadoop/hdfs/lib/log4j-1.2.17.jar
/usr/share/hadoop/hdfs/lib/netty-3.6.2.Final.jar
/usr/share/hadoop/hdfs/lib/netty-all-4.0.23.Final.jar
/usr/share/hadoop/hdfs/lib/protobuf-java-3.2.0.jar
/usr/share/hadoop/hdfs/lib/servlet-api-2.5.jar
/usr/share/hadoop/hdfs/lib/xercesImpl-2.9.1.jar
/usr/share/hadoop/hdfs/lib/xml-apis-1.3.04.jar
/usr/share/hadoop/hdfs/lib/xmlenc-0.52.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-2.7.3-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-2.7.3-test-sources.jar
/usr/share/hadoop/hdfs/templates/hdfs-site.xml
/usr/share/hadoop/hdfs/webapps/datanode/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/datanode/index.html
/usr/share/hadoop/hdfs/webapps/datanode/robots.txt
/usr/share/hadoop/hdfs/webapps/hdfs/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/hdfs/dfshealth.html
/usr/share/hadoop/hdfs/webapps/hdfs/dfshealth.js
/usr/share/hadoop/hdfs/webapps/hdfs/explorer.html
/usr/share/hadoop/hdfs/webapps/hdfs/explorer.js
/usr/share/hadoop/hdfs/webapps/hdfs/index.html
/usr/share/hadoop/hdfs/webapps/journal/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/journal/index.html
/usr/share/hadoop/hdfs/webapps/nfs3/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/secondary/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/secondary/index.html
/usr/share/hadoop/hdfs/webapps/secondary/snn.js
/usr/share/hadoop/hdfs/webapps/secondary/status.html
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.0.2/css/bootstrap.min.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.0.2/fonts/glyphicons-halflings-regular.eot
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.0.2/fonts/glyphicons-halflings-regular.svg
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.0.2/fonts/glyphicons-halflings-regular.ttf
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.0.2/fonts/glyphicons-halflings-regular.woff
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.0.2/js/bootstrap.min.js
/usr/share/hadoop/hdfs/webapps/static/dfs-dust.js
/usr/share/hadoop/hdfs/webapps/static/dust-full-2.0.0.min.js
/usr/share/hadoop/hdfs/webapps/static/dust-helpers-1.1.1.min.js
/usr/share/hadoop/hdfs/webapps/static/hadoop.css
/usr/share/hadoop/hdfs/webapps/static/jquery-1.10.2.min.js
/usr/share/hadoop/httpfs/tomcat/LICENSE
/usr/share/hadoop/httpfs/tomcat/NOTICE
/usr/share/hadoop/httpfs/tomcat/RELEASE-NOTES
/usr/share/hadoop/httpfs/tomcat/RUNNING.txt
/usr/share/hadoop/httpfs/tomcat/bin/bootstrap.jar
/usr/share/hadoop/httpfs/tomcat/bin/catalina-tasks.xml
/usr/share/hadoop/httpfs/tomcat/bin/catalina.bat
/usr/share/hadoop/httpfs/tomcat/bin/catalina.sh
/usr/share/hadoop/httpfs/tomcat/bin/commons-daemon-native.tar.gz
/usr/share/hadoop/httpfs/tomcat/bin/commons-daemon.jar
/usr/share/hadoop/httpfs/tomcat/bin/cpappend.bat
/usr/share/hadoop/httpfs/tomcat/bin/daemon.sh
/usr/share/hadoop/httpfs/tomcat/bin/digest.bat
/usr/share/hadoop/httpfs/tomcat/bin/digest.sh
/usr/share/hadoop/httpfs/tomcat/bin/setclasspath.bat
/usr/share/hadoop/httpfs/tomcat/bin/setclasspath.sh
/usr/share/hadoop/httpfs/tomcat/bin/shutdown.bat
/usr/share/hadoop/httpfs/tomcat/bin/shutdown.sh
/usr/share/hadoop/httpfs/tomcat/bin/startup.bat
/usr/share/hadoop/httpfs/tomcat/bin/startup.sh
/usr/share/hadoop/httpfs/tomcat/bin/tomcat-juli.jar
/usr/share/hadoop/httpfs/tomcat/bin/tomcat-native.tar.gz
/usr/share/hadoop/httpfs/tomcat/bin/tool-wrapper.bat
/usr/share/hadoop/httpfs/tomcat/bin/tool-wrapper.sh
/usr/share/hadoop/httpfs/tomcat/bin/version.bat
/usr/share/hadoop/httpfs/tomcat/bin/version.sh
/usr/share/hadoop/httpfs/tomcat/conf/catalina.policy
/usr/share/hadoop/httpfs/tomcat/conf/catalina.properties
/usr/share/hadoop/httpfs/tomcat/conf/context.xml
/usr/share/hadoop/httpfs/tomcat/conf/logging.properties
/usr/share/hadoop/httpfs/tomcat/conf/server.xml
/usr/share/hadoop/httpfs/tomcat/conf/ssl-server.xml
/usr/share/hadoop/httpfs/tomcat/conf/tomcat-users.xml
/usr/share/hadoop/httpfs/tomcat/conf/web.xml
/usr/share/hadoop/httpfs/tomcat/lib/annotations-api.jar
/usr/share/hadoop/httpfs/tomcat/lib/catalina-ant.jar
/usr/share/hadoop/httpfs/tomcat/lib/catalina-ha.jar
/usr/share/hadoop/httpfs/tomcat/lib/catalina-tribes.jar
/usr/share/hadoop/httpfs/tomcat/lib/catalina.jar
/usr/share/hadoop/httpfs/tomcat/lib/ecj-4.3.1.jar
/usr/share/hadoop/httpfs/tomcat/lib/el-api.jar
/usr/share/hadoop/httpfs/tomcat/lib/jasper-el.jar
/usr/share/hadoop/httpfs/tomcat/lib/jasper.jar
/usr/share/hadoop/httpfs/tomcat/lib/jsp-api.jar
/usr/share/hadoop/httpfs/tomcat/lib/servlet-api.jar
/usr/share/hadoop/httpfs/tomcat/lib/tomcat-coyote.jar
/usr/share/hadoop/httpfs/tomcat/lib/tomcat-dbcp.jar
/usr/share/hadoop/httpfs/tomcat/lib/tomcat-i18n-es.jar
/usr/share/hadoop/httpfs/tomcat/lib/tomcat-i18n-fr.jar
/usr/share/hadoop/httpfs/tomcat/lib/tomcat-i18n-ja.jar
/usr/share/hadoop/httpfs/tomcat/temp/safeToDelete.tmp
/usr/share/hadoop/httpfs/tomcat/webapps/ROOT/WEB-INF/web.xml
/usr/share/hadoop/httpfs/tomcat/webapps/ROOT/index.html
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/META-INF/LICENSE.txt
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/META-INF/NOTICE.txt
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/default-log4j.properties
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/httpfs-default.xml
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/httpfs.properties
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$1.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$2.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$3.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$4.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$5.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$FILE_TYPE.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$HttpFSDataInputStream.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$HttpFSDataOutputStream.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$Operation.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSUtils.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpsFSFileSystem.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/CheckUploadContentTypeFilter.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSAclStatus.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSAppend.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSConcat.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSContentSummary.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSCreate.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSDelete.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSFileChecksum.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSFileStatus.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSGetXAttrs.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSHomeDir.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSListStatus.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSListXAttrs.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSMkdirs.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSModifyAclEntries.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSOpen.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveAcl.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveAclEntries.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveDefaultAcl.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveXAttr.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRename.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetAcl.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetOwner.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetPermission.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetReplication.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetTimes.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetXAttr.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSTruncate.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$StatusPair.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$StatusPairs.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSAuthenticationFilter.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSExceptionProvider.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$AccessTimeParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$AclPermissionParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$BlockSizeParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$DataParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$DestinationParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$FilterParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$GroupParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$LenParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$ModifiedTimeParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$NewLengthParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OffsetParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OperationParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OverwriteParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OwnerParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$PermissionParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$RecursiveParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$ReplicationParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$SourcesParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrEncodingParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrNameParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrSetFlagParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrValueParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSReleaseFilter.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSServer$1.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSServer.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSServerWebApp.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/lang/RunnableCallable.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/lang/XException$ERROR.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/lang/XException.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/BaseService.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/Server$Status.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/Server.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/ServerException$ERROR.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/ServerException.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/Service.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/ServiceException.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccess$FileSystemExecutor.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccess.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccessException$ERROR.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccessException.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Groups.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Instrumentation$Cron.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Instrumentation$Variable.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Instrumentation.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Scheduler.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$1.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$2.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$3.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$4.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$CachedFileSystem.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$FileSystemCachePurger.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$1.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$2.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$3.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$Cron.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$Sampler.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$SamplersRunnable.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$Timer.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$VariableHolder.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/scheduler/SchedulerService$1.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/scheduler/SchedulerService.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/security/GroupsService.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/FileSystemReleaseFilter.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/HostnameFilter.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/MDCFilter.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/ServerWebApp.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/util/Check.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/util/ConfigurationUtils.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/BooleanParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ByteParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/EnumParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/EnumSetParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ExceptionProvider.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/InputStreamEntity.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/IntegerParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/JSONMapProvider.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/JSONProvider.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/LongParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/Param.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/Parameters.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ParametersProvider.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ShortParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/StringParam.class
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/activation-1.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/apacheds-i18n-2.0.0-M15.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/apacheds-kerberos-codec-2.0.0-M15.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/api-asn1-api-1.0.0-M20.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/api-util-1.0.0-M20.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/asm-3.2.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/avro-1.7.4.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-beanutils-1.7.0.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-beanutils-core-1.8.0.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-cli-1.2.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-codec-1.4.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-configuration-1.6.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-daemon-1.0.13.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-digester-1.8.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-io-2.4.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-lang-2.6.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/commons-net-3.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/curator-client-2.7.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/curator-framework-2.7.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/curator-recipes-2.7.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/gson-2.2.4.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/guava-11.0.2.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/hadoop-annotations-2.7.3.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/hadoop-auth-2.7.3.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/hadoop-common-2.7.3.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/hadoop-hdfs-2.7.3.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/htrace-core-3.1.0-incubating.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/httpclient-4.2.5.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/httpcore-4.2.5.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jaxb-api-2.2.2.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jersey-core-1.9.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jersey-json-1.9.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jersey-server-1.9.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jettison-1.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jline-0.9.94.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jsch-0.1.42.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/json-simple-1.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/jsr305-3.0.0.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/leveldbjni-all-1.8.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/log4j-1.2.17.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/netty-3.6.2.Final.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/netty-all-4.0.23.Final.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/paranamer-2.3.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/protobuf-java-3.2.0.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/slf4j-api-1.7.10.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/slf4j-log4j12-1.7.10.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/snappy-java-1.0.4.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/xercesImpl-2.9.1.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/xml-apis-1.3.04.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/xmlenc-0.52.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/xz-1.0.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/lib/zookeeper-3.4.6.jar
/usr/share/hadoop/httpfs/tomcat/webapps/webhdfs/WEB-INF/web.xml
/usr/share/hadoop/kms/tomcat/LICENSE
/usr/share/hadoop/kms/tomcat/NOTICE
/usr/share/hadoop/kms/tomcat/RELEASE-NOTES
/usr/share/hadoop/kms/tomcat/RUNNING.txt
/usr/share/hadoop/kms/tomcat/bin/bootstrap.jar
/usr/share/hadoop/kms/tomcat/bin/catalina-tasks.xml
/usr/share/hadoop/kms/tomcat/bin/catalina.bat
/usr/share/hadoop/kms/tomcat/bin/catalina.sh
/usr/share/hadoop/kms/tomcat/bin/commons-daemon-native.tar.gz
/usr/share/hadoop/kms/tomcat/bin/commons-daemon.jar
/usr/share/hadoop/kms/tomcat/bin/cpappend.bat
/usr/share/hadoop/kms/tomcat/bin/daemon.sh
/usr/share/hadoop/kms/tomcat/bin/digest.bat
/usr/share/hadoop/kms/tomcat/bin/digest.sh
/usr/share/hadoop/kms/tomcat/bin/setclasspath.bat
/usr/share/hadoop/kms/tomcat/bin/setclasspath.sh
/usr/share/hadoop/kms/tomcat/bin/shutdown.bat
/usr/share/hadoop/kms/tomcat/bin/shutdown.sh
/usr/share/hadoop/kms/tomcat/bin/startup.bat
/usr/share/hadoop/kms/tomcat/bin/startup.sh
/usr/share/hadoop/kms/tomcat/bin/tomcat-juli.jar
/usr/share/hadoop/kms/tomcat/bin/tomcat-native.tar.gz
/usr/share/hadoop/kms/tomcat/bin/tool-wrapper.bat
/usr/share/hadoop/kms/tomcat/bin/tool-wrapper.sh
/usr/share/hadoop/kms/tomcat/bin/version.bat
/usr/share/hadoop/kms/tomcat/bin/version.sh
/usr/share/hadoop/kms/tomcat/conf/catalina.policy
/usr/share/hadoop/kms/tomcat/conf/catalina.properties
/usr/share/hadoop/kms/tomcat/conf/context.xml
/usr/share/hadoop/kms/tomcat/conf/logging.properties
/usr/share/hadoop/kms/tomcat/conf/server.xml
/usr/share/hadoop/kms/tomcat/conf/ssl-server.xml.conf
/usr/share/hadoop/kms/tomcat/conf/tomcat-users.xml
/usr/share/hadoop/kms/tomcat/conf/web.xml
/usr/share/hadoop/kms/tomcat/lib/annotations-api.jar
/usr/share/hadoop/kms/tomcat/lib/catalina-ant.jar
/usr/share/hadoop/kms/tomcat/lib/catalina-ha.jar
/usr/share/hadoop/kms/tomcat/lib/catalina-tribes.jar
/usr/share/hadoop/kms/tomcat/lib/catalina.jar
/usr/share/hadoop/kms/tomcat/lib/ecj-4.3.1.jar
/usr/share/hadoop/kms/tomcat/lib/el-api.jar
/usr/share/hadoop/kms/tomcat/lib/jasper-el.jar
/usr/share/hadoop/kms/tomcat/lib/jasper.jar
/usr/share/hadoop/kms/tomcat/lib/jsp-api.jar
/usr/share/hadoop/kms/tomcat/lib/servlet-api.jar
/usr/share/hadoop/kms/tomcat/lib/tomcat-coyote.jar
/usr/share/hadoop/kms/tomcat/lib/tomcat-dbcp.jar
/usr/share/hadoop/kms/tomcat/lib/tomcat-i18n-es.jar
/usr/share/hadoop/kms/tomcat/lib/tomcat-i18n-fr.jar
/usr/share/hadoop/kms/tomcat/lib/tomcat-i18n-ja.jar
/usr/share/hadoop/kms/tomcat/temp/safeToDelete.tmp
/usr/share/hadoop/kms/tomcat/webapps/ROOT/WEB-INF/web.xml
/usr/share/hadoop/kms/tomcat/webapps/ROOT/index.html
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/activation-1.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/apacheds-i18n-2.0.0-M15.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/apacheds-kerberos-codec-2.0.0-M15.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/api-asn1-api-1.0.0-M20.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/api-i18n-1.0.0-M20.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/api-util-1.0.0-M20.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/asm-3.2.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/avro-1.7.4.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-beanutils-1.7.0.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-beanutils-core-1.8.0.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-cli-1.2.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-codec-1.4.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-configuration-1.6.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-digester-1.8.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-io-2.4.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-lang-2.6.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/commons-net-3.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/curator-client-2.7.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/curator-framework-2.7.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/curator-recipes-2.7.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/gson-2.2.4.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/guava-11.0.2.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/hadoop-annotations-2.7.3.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/hadoop-auth-2.7.3.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/hadoop-common-2.7.3.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/hadoop-kms-2.7.3.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/htrace-core-3.1.0-incubating.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/httpclient-4.2.5.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/httpcore-4.2.5.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jaxb-api-2.2.2.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jersey-core-1.9.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jersey-json-1.9.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jersey-server-1.9.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jettison-1.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jetty-util-6.1.26.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jline-0.9.94.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jsch-0.1.42.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jsr305-3.0.0.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/jul-to-slf4j-1.7.10.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/log4j-1.2.17.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/metrics-core-3.0.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/netty-3.6.2.Final.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/paranamer-2.3.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/protobuf-java-3.2.0.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/slf4j-api-1.7.10.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/slf4j-log4j12-1.7.10.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/snappy-java-1.0.4.1.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/xmlenc-0.52.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/xz-1.0.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/lib/zookeeper-3.4.6.jar
/usr/share/hadoop/kms/tomcat/webapps/kms/WEB-INF/web.xml
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-app-2.7.3.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-common-2.7.3.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-core-2.7.3.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-2.7.3.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-plugins-2.7.3.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.7.3-tests.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.7.3.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-shuffle-2.7.3.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.3.jar
/usr/share/hadoop/mapreduce/lib-examples/hsqldb-2.0.0.jar
/usr/share/hadoop/mapreduce/lib/aopalliance-1.0.jar
/usr/share/hadoop/mapreduce/lib/asm-3.2.jar
/usr/share/hadoop/mapreduce/lib/avro-1.7.4.jar
/usr/share/hadoop/mapreduce/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/mapreduce/lib/commons-io-2.4.jar
/usr/share/hadoop/mapreduce/lib/guice-3.0.jar
/usr/share/hadoop/mapreduce/lib/guice-servlet-3.0.jar
/usr/share/hadoop/mapreduce/lib/hadoop-annotations-2.7.3.jar
/usr/share/hadoop/mapreduce/lib/hamcrest-core-1.3.jar
/usr/share/hadoop/mapreduce/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/mapreduce/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/mapreduce/lib/javax.inject-1.jar
/usr/share/hadoop/mapreduce/lib/jersey-core-1.9.jar
/usr/share/hadoop/mapreduce/lib/jersey-guice-1.9.jar
/usr/share/hadoop/mapreduce/lib/jersey-server-1.9.jar
/usr/share/hadoop/mapreduce/lib/junit-4.11.jar
/usr/share/hadoop/mapreduce/lib/leveldbjni-all-1.8.jar
/usr/share/hadoop/mapreduce/lib/log4j-1.2.17.jar
/usr/share/hadoop/mapreduce/lib/netty-3.6.2.Final.jar
/usr/share/hadoop/mapreduce/lib/paranamer-2.3.jar
/usr/share/hadoop/mapreduce/lib/protobuf-java-3.2.0.jar
/usr/share/hadoop/mapreduce/lib/snappy-java-1.0.4.1.jar
/usr/share/hadoop/mapreduce/lib/xz-1.0.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-app-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-app-2.7.3-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-common-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-common-2.7.3-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-core-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-core-2.7.3-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-2.7.3-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-plugins-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-plugins-2.7.3-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-jobclient-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-jobclient-2.7.3-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-shuffle-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-shuffle-2.7.3-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-examples-2.7.3-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-examples-2.7.3-test-sources.jar
/usr/share/hadoop/tools/lib/activation-1.1.jar
/usr/share/hadoop/tools/lib/apacheds-i18n-2.0.0-M15.jar
/usr/share/hadoop/tools/lib/apacheds-kerberos-codec-2.0.0-M15.jar
/usr/share/hadoop/tools/lib/api-asn1-api-1.0.0-M20.jar
/usr/share/hadoop/tools/lib/api-util-1.0.0-M20.jar
/usr/share/hadoop/tools/lib/asm-3.2.jar
/usr/share/hadoop/tools/lib/avro-1.7.4.jar
/usr/share/hadoop/tools/lib/aws-java-sdk-1.7.4.jar
/usr/share/hadoop/tools/lib/aws-java-sdk-1.7.4.jar
/usr/share/hadoop/tools/lib/azure-storage-2.0.0.jar
/usr/share/hadoop/tools/lib/commons-beanutils-1.7.0.jar
/usr/share/hadoop/tools/lib/commons-beanutils-core-1.8.0.jar
/usr/share/hadoop/tools/lib/commons-cli-1.2.jar
/usr/share/hadoop/tools/lib/commons-codec-1.4.jar
/usr/share/hadoop/tools/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/tools/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/tools/lib/commons-configuration-1.6.jar
/usr/share/hadoop/tools/lib/commons-digester-1.8.jar
/usr/share/hadoop/tools/lib/commons-httpclient-3.1.jar
/usr/share/hadoop/tools/lib/commons-io-2.4.jar
/usr/share/hadoop/tools/lib/commons-lang-2.6.jar
/usr/share/hadoop/tools/lib/commons-lang3-3.3.2.jar
/usr/share/hadoop/tools/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/tools/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/tools/lib/commons-net-3.1.jar
/usr/share/hadoop/tools/lib/curator-client-2.7.1.jar
/usr/share/hadoop/tools/lib/curator-framework-2.7.1.jar
/usr/share/hadoop/tools/lib/curator-recipes-2.7.1.jar
/usr/share/hadoop/tools/lib/gson-2.2.4.jar
/usr/share/hadoop/tools/lib/guava-11.0.2.jar
/usr/share/hadoop/tools/lib/hadoop-ant-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-archives-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-auth-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-aws-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-azure-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-datajoin-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-distcp-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-extras-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-gridmix-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-openstack-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-rumen-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-sls-2.7.3.jar
/usr/share/hadoop/tools/lib/hadoop-streaming-2.7.3.jar
/usr/share/hadoop/tools/lib/hamcrest-core-1.3.jar
/usr/share/hadoop/tools/lib/htrace-core-3.1.0-incubating.jar
/usr/share/hadoop/tools/lib/httpclient-4.2.5.jar
/usr/share/hadoop/tools/lib/httpcore-4.2.5.jar
/usr/share/hadoop/tools/lib/jackson-annotations-2.2.3.jar
/usr/share/hadoop/tools/lib/jackson-core-2.2.3.jar
/usr/share/hadoop/tools/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/tools/lib/jackson-databind-2.2.3.jar
/usr/share/hadoop/tools/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/tools/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/tools/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/tools/lib/java-xmlbuilder-0.4.jar
/usr/share/hadoop/tools/lib/jaxb-api-2.2.2.jar
/usr/share/hadoop/tools/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/tools/lib/jersey-core-1.9.jar
/usr/share/hadoop/tools/lib/jersey-json-1.9.jar
/usr/share/hadoop/tools/lib/jersey-server-1.9.jar
/usr/share/hadoop/tools/lib/jets3t-0.9.0.jar
/usr/share/hadoop/tools/lib/jettison-1.1.jar
/usr/share/hadoop/tools/lib/jetty-6.1.26.jar
/usr/share/hadoop/tools/lib/jetty-util-6.1.26.jar
/usr/share/hadoop/tools/lib/joda-time-2.9.9.jar
/usr/share/hadoop/tools/lib/jsch-0.1.42.jar
/usr/share/hadoop/tools/lib/jsp-api-2.1.jar
/usr/share/hadoop/tools/lib/jsr305-3.0.0.jar
/usr/share/hadoop/tools/lib/junit-4.11.jar
/usr/share/hadoop/tools/lib/log4j-1.2.17.jar
/usr/share/hadoop/tools/lib/metrics-core-3.0.1.jar
/usr/share/hadoop/tools/lib/mockito-all-1.8.5.jar
/usr/share/hadoop/tools/lib/netty-3.6.2.Final.jar
/usr/share/hadoop/tools/lib/paranamer-2.3.jar
/usr/share/hadoop/tools/lib/protobuf-java-3.2.0.jar
/usr/share/hadoop/tools/lib/servlet-api-2.5.jar
/usr/share/hadoop/tools/lib/snappy-java-1.0.4.1.jar
/usr/share/hadoop/tools/lib/stax-api-1.0-2.jar
/usr/share/hadoop/tools/lib/xmlenc-0.52.jar
/usr/share/hadoop/tools/lib/xz-1.0.jar
/usr/share/hadoop/tools/lib/zookeeper-3.4.6.jar
/usr/share/hadoop/tools/sls/bin/rumen2sls.sh
/usr/share/hadoop/tools/sls/bin/slsrun.sh
/usr/share/hadoop/tools/sls/html/css/bootstrap-responsive.min.css
/usr/share/hadoop/tools/sls/html/css/bootstrap.min.css
/usr/share/hadoop/tools/sls/html/js/thirdparty/bootstrap.min.js
/usr/share/hadoop/tools/sls/html/js/thirdparty/d3-LICENSE
/usr/share/hadoop/tools/sls/html/js/thirdparty/d3.v3.js
/usr/share/hadoop/tools/sls/html/js/thirdparty/jquery.js
/usr/share/hadoop/tools/sls/html/showSimulationTrace.html
/usr/share/hadoop/tools/sls/html/simulate.html.template
/usr/share/hadoop/tools/sls/html/simulate.info.html.template
/usr/share/hadoop/tools/sls/html/track.html.template
/usr/share/hadoop/tools/sls/sample-conf/capacity-scheduler.xml
/usr/share/hadoop/tools/sls/sample-conf/fair-scheduler.xml
/usr/share/hadoop/tools/sls/sample-conf/log4j.properties
/usr/share/hadoop/tools/sls/sample-conf/sls-runner.xml
/usr/share/hadoop/tools/sls/sample-conf/yarn-site.xml
/usr/share/hadoop/tools/sls/sample-data/2jobs2min-rumen-jh.json
/usr/share/hadoop/tools/sources/hadoop-archives-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archives-2.7.3-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-datajoin-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-datajoin-2.7.3-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-distcp-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-distcp-2.7.3-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-extras-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-extras-2.7.3-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-gridmix-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-gridmix-2.7.3-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-rumen-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-rumen-2.7.3-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-sls-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-sls-2.7.3-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-streaming-2.7.3-sources.jar
/usr/share/hadoop/tools/sources/hadoop-streaming-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/hadoop-yarn-api-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-applications-distributedshell-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-applications-unmanaged-am-launcher-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-client-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-common-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-registry-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-applicationhistoryservice-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-common-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-nodemanager-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-resourcemanager-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-sharedcachemanager-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-tests-2.7.3.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-web-proxy-2.7.3.jar
/usr/share/hadoop/yarn/lib/activation-1.1.jar
/usr/share/hadoop/yarn/lib/aopalliance-1.0.jar
/usr/share/hadoop/yarn/lib/asm-3.2.jar
/usr/share/hadoop/yarn/lib/commons-cli-1.2.jar
/usr/share/hadoop/yarn/lib/commons-codec-1.4.jar
/usr/share/hadoop/yarn/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/yarn/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/yarn/lib/commons-io-2.4.jar
/usr/share/hadoop/yarn/lib/commons-lang-2.6.jar
/usr/share/hadoop/yarn/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/yarn/lib/guava-11.0.2.jar
/usr/share/hadoop/yarn/lib/guice-3.0.jar
/usr/share/hadoop/yarn/lib/guice-servlet-3.0.jar
/usr/share/hadoop/yarn/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/yarn/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/yarn/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/yarn/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/yarn/lib/javax.inject-1.jar
/usr/share/hadoop/yarn/lib/jaxb-api-2.2.2.jar
/usr/share/hadoop/yarn/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/yarn/lib/jersey-client-1.9.jar
/usr/share/hadoop/yarn/lib/jersey-core-1.9.jar
/usr/share/hadoop/yarn/lib/jersey-guice-1.9.jar
/usr/share/hadoop/yarn/lib/jersey-json-1.9.jar
/usr/share/hadoop/yarn/lib/jersey-server-1.9.jar
/usr/share/hadoop/yarn/lib/jettison-1.1.jar
/usr/share/hadoop/yarn/lib/jetty-6.1.26.jar
/usr/share/hadoop/yarn/lib/jetty-util-6.1.26.jar
/usr/share/hadoop/yarn/lib/jsr305-3.0.0.jar
/usr/share/hadoop/yarn/lib/leveldbjni-all-1.8.jar
/usr/share/hadoop/yarn/lib/log4j-1.2.17.jar
/usr/share/hadoop/yarn/lib/netty-3.6.2.Final.jar
/usr/share/hadoop/yarn/lib/protobuf-java-3.2.0.jar
/usr/share/hadoop/yarn/lib/servlet-api-2.5.jar
/usr/share/hadoop/yarn/lib/stax-api-1.0-2.jar
/usr/share/hadoop/yarn/lib/xz-1.0.jar
/usr/share/hadoop/yarn/lib/zookeeper-3.4.6-tests.jar
/usr/share/hadoop/yarn/lib/zookeeper-3.4.6.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-api-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-api-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-distributedshell-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-distributedshell-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-unmanaged-am-launcher-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-unmanaged-am-launcher-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-client-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-client-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-common-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-common-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-applicationhistoryservice-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-applicationhistoryservice-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-common-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-common-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-nodemanager-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-nodemanager-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-resourcemanager-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-resourcemanager-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-tests-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-tests-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-web-proxy-2.7.3-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-web-proxy-2.7.3-test-sources.jar
/usr/share/hadoop/yarn/test/hadoop-yarn-server-tests-2.7.3-tests.jar
