Name     : apache-hadoop
Version  : 3.2.0
Release  : 28
URL      : http://apache.cs.utah.edu/hadoop/common/hadoop-3.2.0/hadoop-3.2.0-src.tar.gz
Source0  : http://apache.cs.utah.edu/hadoop/common/hadoop-3.2.0/hadoop-3.2.0-src.tar.gz
Source1  : http://archive.apache.org/dist/tomcat/tomcat-6/v6.0.48/bin/apache-tomcat-6.0.48.tar.gz
Source2  : https://repo.maven.apache.org/maven2/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
BuildRequires : cyrus-sasl
BuildRequires : cyrus-sasl-dev
BuildRequires : hadoop-dep
BuildRequires : openjdk11
BuildRequires : openjdk11-dev
BuildRequires : protobuf
BuildRequires : protobuf-dev
Buildrequires : apache-maven
BuildRequires : cmake
BuildRequires : zlib-dev
BuildRequires : openssl-dev
Patch0   : 0001-Integrate-JDK11.patch
Patch1   : 0001-Java_home-on-CLR.patch
Patch2   : HADOOP-11364.01.patch
Patch3   : 0001-Stateless-v2.patch
Patch4   : 0001-Change-protobuf-version.patch
Patch5   : protobuf3.patch
Patch6   : protobuf-3.6.1-hadoop-3.2.0-On-CLR.patch
Patch7   : 0001-YARN-8498.-Yarn-NodeManager-OOM-Listener-Fails-Compi.patch

%description

%prep
%setup -q -n hadoop-3.2.0-src
%patch0 -p1
%patch1 -p1
# https://issues.apache.org/jira/browse/YARN-4714
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1

%build
mkdir -p %{buildroot}
cp -r /usr/share/apache-hadoop/.m2 %{buildroot}/.m2

# Copy apache-tomcat
#mkdir hadoop-common-project/hadoop-kms/downloads
#mkdir hadoop-hdfs-project/hadoop-hdfs-httpfs/downloads
cp %{SOURCE1} hadoop-common-project/hadoop-kms/downloads
cp %{SOURCE1} hadoop-hdfs-project/hadoop-hdfs-httpfs/downloads

# Build Hadoop
# TODO compile Hadoop with -Pdocs, but fails
# TODO compile Hadoop with -Pnative, but fails
export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk
mvn package -o -Pnative -Pdist -DskipTests -Dtar -Danimal.sniffer.skip=true -Dmaven.javadoc.skip=true -Djavac.version=11 -Dguava.version=19.0 -Dmaven.plugin-tools.version=3.6.0 -Dmaven.repo.local=%{buildroot}/.m2/repository

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/defaults/hadoop
mkdir -p %{buildroot}/usr/share/doc/hadoop
tar -xf hadoop-dist/target/hadoop-*.tar.gz -C %{buildroot}/usr --strip-components=1
mv %{buildroot}/usr/*.txt %{buildroot}/usr/share/doc/hadoop
mv %{buildroot}/usr/etc/* %{buildroot}/usr/share/defaults

# Remove *.cmd files 
find %{buildroot}/usr -iname *.cmd -delete
find %{buildroot}/usr -iname *.orig -delete

# Fix java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup
cp %{SOURCE2} %{buildroot}/usr/share/hadoop/common/lib/

%files
%defattr(-,root,root,-)
/usr/include/Pipes.hh
/usr/include/hdfs.h
/usr/include/StringUtils.hh
/usr/include/SerialUtils.hh
/usr/include/TemplateFactory.hh
/usr/share/doc/hadoop/README.txt
/usr/share/doc/hadoop/LICENSE.txt
/usr/share/doc/hadoop/NOTICE.txt
/usr/share/hadoop/client/hadoop-client-minicluster-3.2.0.jar
/usr/share/hadoop/client/hadoop-client-api-3.2.0.jar
/usr/share/hadoop/client/hadoop-client-runtime-3.2.0.jar
/usr/share/hadoop/tools/resourceestimator/conf/resourceestimator-config.xml
/usr/share/hadoop/tools/resourceestimator/bin/start-estimator.sh
/usr/share/hadoop/tools/resourceestimator/bin/estimator.sh
/usr/share/hadoop/tools/resourceestimator/bin/stop-estimator.sh
/usr/share/hadoop/tools/resourceestimator/data/resourceEstimatorService.txt
/usr/share/hadoop/tools/sources/hadoop-streaming-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-rumen-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-streaming-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-datajoin-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-rumen-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-distcp-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-resourceestimator-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-gridmix-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-distcp-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-sls-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archives-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-gridmix-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-datajoin-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-sls-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-extras-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-resourceestimator-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archive-logs-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archive-logs-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-extras-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archives-3.2.0-sources.jar
/usr/share/hadoop/tools/lib/hadoop-sls-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-aliyun-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-extras-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-aws-3.2.0.jar
/usr/share/hadoop/tools/lib/lz4-1.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-kafka-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-rumen-3.2.0.jar
/usr/share/hadoop/tools/lib/ojalgo-43.0.jar
/usr/share/hadoop/tools/lib/hadoop-archive-logs-3.2.0.jar
/usr/share/hadoop/tools/lib/aliyun-sdk-oss-2.8.3.jar
/usr/share/hadoop/tools/lib/kafka-clients-0.8.2.1.jar
/usr/share/hadoop/tools/lib/hadoop-azure-datalake-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-resourceestimator-3.2.0.jar
/usr/share/hadoop/tools/lib/wildfly-openssl-1.0.4.Final.jar
/usr/share/hadoop/tools/lib/hadoop-gridmix-3.2.0.jar
/usr/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.375.jar
/usr/share/hadoop/tools/lib/hadoop-streaming-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-archives-3.2.0.jar
/usr/share/hadoop/tools/lib/azure-keyvault-core-1.0.0.jar
/usr/share/hadoop/tools/lib/hadoop-openstack-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-distcp-3.2.0.jar
/usr/share/hadoop/tools/lib/azure-storage-7.0.0.jar
/usr/share/hadoop/tools/lib/hadoop-datajoin-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-fs2img-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-azure-3.2.0.jar
/usr/share/hadoop/tools/lib/jdom-1.1.jar
/usr/share/hadoop/tools/lib/azure-data-lake-store-sdk-2.2.9.jar
/usr/share/hadoop/tools/sls/html/css/bootstrap-responsive.min.css
/usr/share/hadoop/tools/sls/html/css/bootstrap.min.css
/usr/share/hadoop/tools/sls/html/simulate.html.template
/usr/share/hadoop/tools/sls/html/track.html.template
/usr/share/hadoop/tools/sls/html/showSimulationTrace.html
/usr/share/hadoop/tools/sls/html/simulate.info.html.template
/usr/share/hadoop/tools/sls/html/js/thirdparty/d3.v3.js
/usr/share/hadoop/tools/sls/html/js/thirdparty/bootstrap.min.js
/usr/share/hadoop/tools/sls/html/js/thirdparty/d3-LICENSE
/usr/share/hadoop/tools/sls/html/js/thirdparty/jquery.js
/usr/share/hadoop/tools/sls/bin/slsrun.sh
/usr/share/hadoop/tools/sls/bin/rumen2sls.sh
/usr/share/hadoop/tools/sls/sample-conf/fair-scheduler.xml
/usr/share/hadoop/tools/sls/sample-conf/log4j.properties
/usr/share/hadoop/tools/sls/sample-conf/sls-runner.xml
/usr/share/hadoop/tools/sls/sample-conf/yarn-site.xml
/usr/share/hadoop/tools/sls/sample-conf/capacity-scheduler.xml
/usr/share/hadoop/tools/sls/sample-data/2jobs2min-rumen-jh.json
/usr/share/hadoop/yarn/hadoop-yarn-server-timeline-pluginstorage-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-api-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-applications-unmanaged-am-launcher-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-hbase-common-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/test/hadoop-yarn-server-timelineservice-hbase-tests-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-hbase-client-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-hbase-coprocessor-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/lib/commons-csv-1.0.jar
/usr/share/hadoop/yarn/timelineservice/lib/jcodings-1.0.13.jar
/usr/share/hadoop/yarn/timelineservice/lib/metrics-core-2.2.0.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-common-1.2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-protocol-1.2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/htrace-core-3.1.0-incubating.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-annotations-1.2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/commons-lang-2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/joni-2.1.2.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-client-1.2.6.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-web-proxy-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-submarine-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-services-core-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-nodemanager-3.2.0.jar
/usr/share/hadoop/yarn/test/hadoop-yarn-server-tests-3.2.0-tests.jar
/usr/share/hadoop/yarn/hadoop-yarn-registry-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-common-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-applicationhistoryservice-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-tests-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-router-3.2.0.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-nodemanager-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-common-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-resourcemanager-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-nodemanager-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-common-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-api-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-tests-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-unmanaged-am-launcher-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-applicationhistoryservice-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-core-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-client-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-web-proxy-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-applicationhistoryservice-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-web-proxy-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-api-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-distributedshell-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-api-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-distributedshell-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-resourcemanager-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-common-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-client-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-core-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-tests-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-unmanaged-am-launcher-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-api-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-common-3.2.0-sources.jar
/usr/share/hadoop/yarn/hadoop-yarn-client-3.2.0.jar
/usr/share/hadoop/yarn/lib/mssql-jdbc-6.2.1.jre7.jar
/usr/share/hadoop/yarn/lib/guice-4.0.jar
/usr/share/hadoop/yarn/lib/swagger-annotations-1.5.4.jar
/usr/share/hadoop/yarn/lib/json-io-2.5.1.jar
/usr/share/hadoop/yarn/lib/jersey-guice-1.19.jar
/usr/share/hadoop/yarn/lib/aopalliance-1.0.jar
/usr/share/hadoop/yarn/lib/jackson-jaxrs-base-2.9.5.jar
/usr/share/hadoop/yarn/lib/javax.inject-1.jar
/usr/share/hadoop/yarn/lib/ehcache-3.3.1.jar
/usr/share/hadoop/yarn/lib/fst-2.50.jar
/usr/share/hadoop/yarn/lib/guice-servlet-4.0.jar
/usr/share/hadoop/yarn/lib/jackson-jaxrs-json-provider-2.9.5.jar
/usr/share/hadoop/yarn/lib/objenesis-1.0.jar
/usr/share/hadoop/yarn/lib/jersey-client-1.19.jar
/usr/share/hadoop/yarn/lib/java-util-1.9.0.jar
/usr/share/hadoop/yarn/lib/HikariCP-java7-2.4.12.jar
/usr/share/hadoop/yarn/lib/snakeyaml-1.16.jar
/usr/share/hadoop/yarn/lib/jackson-module-jaxb-annotations-2.9.5.jar
/usr/share/hadoop/yarn/lib/metrics-core-3.2.4.jar
/usr/share/hadoop/yarn/lib/geronimo-jcache_1.0_spec-1.0-alpha-1.jar
/usr/share/hadoop/yarn/hadoop-yarn-common-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-resourcemanager-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-applications-distributedshell-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-sharedcachemanager-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-services-api-3.2.0.jar
/usr/share/hadoop/yarn/yarn-service-examples/httpd/httpd-proxy.conf
/usr/share/hadoop/yarn/yarn-service-examples/httpd/httpd.json
/usr/share/hadoop/yarn/yarn-service-examples/sleeper/sleeper.json
/usr/share/hadoop/yarn/yarn-service-examples/httpd-no-dns/httpd-no-dns.json
/usr/share/hadoop/yarn/yarn-service-examples/httpd-no-dns/httpd-proxy-no-dns.conf
/usr/share/hadoop/common/hadoop-common-3.2.0-tests.jar
/usr/share/hadoop/common/hadoop-kms-3.2.0.jar
/usr/share/hadoop/common/webapps/static/hadoop.css.gz
/usr/share/hadoop/common/hadoop-common-3.2.0.jar
/usr/share/hadoop/common/hadoop-nfs-3.2.0.jar
/usr/share/hadoop/common/sources/hadoop-common-3.2.0-sources.jar
/usr/share/hadoop/common/sources/hadoop-common-3.2.0-test-sources.jar
/usr/share/hadoop/common/lib/jcip-annotations-1.0-1.jar
/usr/share/hadoop/common/lib/jetty-servlet-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/token-provider-1.0.1.jar
/usr/share/hadoop/common/lib/jetty-webapp-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/hadoop-auth-3.2.0.jar
/usr/share/hadoop/common/lib/dnsjava-2.1.7.jar
/usr/share/hadoop/common/lib/stax2-api-3.1.4.jar
/usr/share/hadoop/common/lib/asm-5.0.4.jar
/usr/share/hadoop/common/lib/kerby-pkix-1.0.1.jar
/usr/share/hadoop/common/lib/netty-all-4.0.23.Final.jar
/usr/share/hadoop/common/lib/curator-framework-2.12.0.jar
/usr/share/hadoop/common/lib/xz-1.0.jar
/usr/share/hadoop/common/lib/jetty-http-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jackson-databind-2.9.5.jar
/usr/share/hadoop/common/lib/commons-net-3.6.jar
/usr/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar
/usr/share/hadoop/common/lib/jul-to-slf4j-1.7.25.jar
/usr/share/hadoop/common/lib/kerby-asn1-1.0.1.jar
/usr/share/hadoop/common/lib/gson-2.2.4.jar
/usr/share/hadoop/common/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/common/lib/jersey-server-1.19.jar
/usr/share/hadoop/common/lib/jackson-annotations-2.9.5.jar
/usr/share/hadoop/common/lib/commons-lang3-3.7.jar
/usr/share/hadoop/common/lib/netty-3.10.5.Final.jar
/usr/share/hadoop/common/lib/jersey-servlet-1.19.jar
/usr/share/hadoop/common/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/common/lib/kerb-core-1.0.1.jar
/usr/share/hadoop/common/lib/paranamer-2.3.jar
/usr/share/hadoop/common/lib/jackson-core-2.9.5.jar
/usr/share/hadoop/common/lib/jetty-security-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/javax.servlet-api-3.1.0.jar
/usr/share/hadoop/common/lib/hadoop-annotations-3.2.0.jar
/usr/share/hadoop/common/lib/jetty-util-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-xml-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jsch-0.1.54.jar
/usr/share/hadoop/common/lib/commons-codec-1.11.jar
/usr/share/hadoop/common/lib/kerb-admin-1.0.1.jar
/usr/share/hadoop/common/lib/jettison-1.1.jar
/usr/share/hadoop/common/lib/jsp-api-2.1.jar
/usr/share/hadoop/common/lib/log4j-1.2.17.jar
/usr/share/hadoop/common/lib/kerb-common-1.0.1.jar
/usr/share/hadoop/common/lib/jetty-io-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/curator-recipes-2.12.0.jar
/usr/share/hadoop/common/lib/kerb-identity-1.0.1.jar
/usr/share/hadoop/common/lib/httpcore-4.4.4.jar
/usr/share/hadoop/common/lib/commons-cli-1.2.jar
/usr/share/hadoop/common/lib/httpclient-4.5.2.jar
/usr/share/hadoop/common/lib/commons-beanutils-1.9.3.jar
/usr/share/hadoop/common/lib/kerby-xdr-1.0.1.jar
/usr/share/hadoop/common/lib/jetty-server-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jaxb-api-2.2.11.jar
/usr/share/hadoop/common/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/common/lib/javax.activation-api-1.2.0.jar
/usr/share/hadoop/common/lib/kerb-crypto-1.0.1.jar
/usr/share/hadoop/common/lib/commons-io-2.5.jar
/usr/share/hadoop/common/lib/kerb-util-1.0.1.jar
/usr/share/hadoop/common/lib/json-smart-2.3.jar
/usr/share/hadoop/common/lib/guava-19.0.jar
/usr/share/hadoop/common/lib/nimbus-jose-jwt-4.41.1.jar
/usr/share/hadoop/common/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/common/lib/accessors-smart-1.2.jar
/usr/share/hadoop/common/lib/commons-configuration2-2.1.1.jar
/usr/share/hadoop/common/lib/jsr311-api-1.1.1.jar
/usr/share/hadoop/common/lib/woodstox-core-5.0.3.jar
/usr/share/hadoop/common/lib/zookeeper-3.4.13.jar
/usr/share/hadoop/common/lib/kerb-server-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-client-1.0.1.jar
/usr/share/hadoop/common/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/common/lib/audience-annotations-0.5.0.jar
/usr/share/hadoop/common/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/common/lib/protobuf-java-3.6.1.jar
/usr/share/hadoop/common/lib/snappy-java-1.0.5.jar
/usr/share/hadoop/common/lib/re2j-1.1.jar
/usr/share/hadoop/common/lib/slf4j-api-1.7.25.jar
/usr/share/hadoop/common/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/common/lib/kerby-util-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-simplekdc-1.0.1.jar
/usr/share/hadoop/common/lib/metrics-core-3.2.4.jar
/usr/share/hadoop/common/lib/jsr305-3.0.0.jar
/usr/share/hadoop/common/lib/htrace-core4-4.1.0-incubating.jar
/usr/share/hadoop/common/lib/jersey-core-1.19.jar
/usr/share/hadoop/common/lib/jersey-json-1.19.jar
/usr/share/hadoop/common/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/common/lib/commons-text-1.4.jar
/usr/share/hadoop/common/lib/avro-1.7.7.jar
/usr/share/hadoop/common/lib/curator-client-2.12.0.jar
/usr/share/hadoop/common/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/common/lib/kerby-config-1.0.1.jar
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.6.0.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.8.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.17.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.0.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.8.2.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.2.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.2.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.2.xml
/usr/share/hadoop/common/jdiff/hadoop-core_0.21.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.3.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.8.3.xml
/usr/share/hadoop/common/jdiff/hadoop-core_0.22.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.1.xml
/usr/share/hadoop/common/jdiff/hadoop-core_0.20.0.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.7.2.xml
/usr/share/hadoop/common/jdiff/Null.java
/usr/share/hadoop/hdfs/hadoop-hdfs-native-client-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-nfs-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-rbf-3.2.0-tests.jar
/usr/share/hadoop/hdfs/webapps/datanode/datanode.html
/usr/share/hadoop/hdfs/webapps/datanode/dn.js
/usr/share/hadoop/hdfs/webapps/datanode/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/datanode/robots.txt
/usr/share/hadoop/hdfs/webapps/datanode/index.html
/usr/share/hadoop/hdfs/webapps/static/rest-csrf.js
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.js
/usr/share/hadoop/hdfs/webapps/static/json-bignum.js
/usr/share/hadoop/hdfs/webapps/static/jquery.dataTables.min.js
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.css
/usr/share/hadoop/hdfs/webapps/static/d3-v4.1.1.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/json-bignum.js.gz
/usr/share/hadoop/hdfs/webapps/static/d3-v4.1.1.min.js
/usr/share/hadoop/hdfs/webapps/static/moment.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/dust-helpers-1.1.1.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/dfs-dust.js
/usr/share/hadoop/hdfs/webapps/static/rest-csrf.js.gz
/usr/share/hadoop/hdfs/webapps/static/rbf.css
/usr/share/hadoop/hdfs/webapps/static/hadoop.css.gz
/usr/share/hadoop/hdfs/webapps/static/hadoop.css
/usr/share/hadoop/hdfs/webapps/static/moment.min.js
/usr/share/hadoop/hdfs/webapps/static/dust-helpers-1.1.1.min.js
/usr/share/hadoop/hdfs/webapps/static/dust-full-2.0.0.min.js
/usr/share/hadoop/hdfs/webapps/static/dfs-dust.js.gz
/usr/share/hadoop/hdfs/webapps/static/jquery-3.3.1.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.css.gz
/usr/share/hadoop/hdfs/webapps/static/jquery-3.3.1.min.js
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.js.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.min.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-editable.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-editable.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.min.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.min.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.min.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.min.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.min.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff2
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.svg
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.eot
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.ttf
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap-editable.min.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.js.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap-editable.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/npm.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.min.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/npm.js.gz
/usr/share/hadoop/hdfs/webapps/static/dust-full-2.0.0.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/jquery.dataTables.min.js.gz
/usr/share/hadoop/hdfs/webapps/nfs3/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/router/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/router/robots.txt
/usr/share/hadoop/hdfs/webapps/router/index.html
/usr/share/hadoop/hdfs/webapps/router/federationhealth.html
/usr/share/hadoop/hdfs/webapps/router/federationhealth.js
/usr/share/hadoop/hdfs/webapps/secondary/status.html
/usr/share/hadoop/hdfs/webapps/secondary/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/secondary/robots.txt
/usr/share/hadoop/hdfs/webapps/secondary/index.html
/usr/share/hadoop/hdfs/webapps/secondary/snn.js
/usr/share/hadoop/hdfs/webapps/journal/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/journal/robots.txt
/usr/share/hadoop/hdfs/webapps/journal/index.html
/usr/share/hadoop/hdfs/webapps/hdfs/explorer.html
/usr/share/hadoop/hdfs/webapps/hdfs/dfshealth.js
/usr/share/hadoop/hdfs/webapps/hdfs/explorer.js
/usr/share/hadoop/hdfs/webapps/hdfs/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/hdfs/robots.txt
/usr/share/hadoop/hdfs/webapps/hdfs/dfshealth.html
/usr/share/hadoop/hdfs/webapps/hdfs/index.html
/usr/share/hadoop/hdfs/hadoop-hdfs-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-native-client-3.2.0-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-client-3.2.0-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-client-3.2.0.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-rbf-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-rbf-3.2.0-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-3.2.0-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-native-client-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-client-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-native-client-3.2.0-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-client-3.2.0-sources.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-rbf-3.2.0.jar
/usr/share/hadoop/hdfs/lib/jetty-util-ajax-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jcip-annotations-1.0-1.jar
/usr/share/hadoop/hdfs/lib/netty-all-4.0.52.Final.jar
/usr/share/hadoop/hdfs/lib/jetty-servlet-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/token-provider-1.0.1.jar
/usr/share/hadoop/hdfs/lib/jetty-webapp-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/hadoop-auth-3.2.0.jar
/usr/share/hadoop/hdfs/lib/dnsjava-2.1.7.jar
/usr/share/hadoop/hdfs/lib/stax2-api-3.1.4.jar
/usr/share/hadoop/hdfs/lib/asm-5.0.4.jar
/usr/share/hadoop/hdfs/lib/kerby-pkix-1.0.1.jar
/usr/share/hadoop/hdfs/lib/curator-framework-2.12.0.jar
/usr/share/hadoop/hdfs/lib/xz-1.0.jar
/usr/share/hadoop/hdfs/lib/jetty-http-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jackson-databind-2.9.5.jar
/usr/share/hadoop/hdfs/lib/commons-net-3.6.jar
/usr/share/hadoop/hdfs/lib/kerby-asn1-1.0.1.jar
/usr/share/hadoop/hdfs/lib/gson-2.2.4.jar
/usr/share/hadoop/hdfs/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/hdfs/lib/jersey-server-1.19.jar
/usr/share/hadoop/hdfs/lib/jackson-annotations-2.9.5.jar
/usr/share/hadoop/hdfs/lib/commons-lang3-3.7.jar
/usr/share/hadoop/hdfs/lib/netty-3.10.5.Final.jar
/usr/share/hadoop/hdfs/lib/jersey-servlet-1.19.jar
/usr/share/hadoop/hdfs/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/hdfs/lib/kerb-core-1.0.1.jar
/usr/share/hadoop/hdfs/lib/paranamer-2.3.jar
/usr/share/hadoop/hdfs/lib/jackson-core-2.9.5.jar
/usr/share/hadoop/hdfs/lib/jetty-security-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/javax.servlet-api-3.1.0.jar
/usr/share/hadoop/hdfs/lib/hadoop-annotations-3.2.0.jar
/usr/share/hadoop/hdfs/lib/jetty-util-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-xml-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jsch-0.1.54.jar
/usr/share/hadoop/hdfs/lib/commons-codec-1.11.jar
/usr/share/hadoop/hdfs/lib/kerb-admin-1.0.1.jar
/usr/share/hadoop/hdfs/lib/jettison-1.1.jar
/usr/share/hadoop/hdfs/lib/log4j-1.2.17.jar
/usr/share/hadoop/hdfs/lib/kerb-common-1.0.1.jar
/usr/share/hadoop/hdfs/lib/jetty-io-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/curator-recipes-2.12.0.jar
/usr/share/hadoop/hdfs/lib/kerb-identity-1.0.1.jar
/usr/share/hadoop/hdfs/lib/httpcore-4.4.4.jar
/usr/share/hadoop/hdfs/lib/commons-cli-1.2.jar
/usr/share/hadoop/hdfs/lib/httpclient-4.5.2.jar
/usr/share/hadoop/hdfs/lib/commons-beanutils-1.9.3.jar
/usr/share/hadoop/hdfs/lib/kerby-xdr-1.0.1.jar
/usr/share/hadoop/hdfs/lib/jetty-server-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jaxb-api-2.2.11.jar
/usr/share/hadoop/hdfs/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/hdfs/lib/javax.activation-api-1.2.0.jar
/usr/share/hadoop/hdfs/lib/kerb-crypto-1.0.1.jar
/usr/share/hadoop/hdfs/lib/commons-io-2.5.jar
/usr/share/hadoop/hdfs/lib/kerb-util-1.0.1.jar
/usr/share/hadoop/hdfs/lib/json-smart-2.3.jar
/usr/share/hadoop/hdfs/lib/guava-19.0.jar
/usr/share/hadoop/hdfs/lib/json-simple-1.1.1.jar
/usr/share/hadoop/hdfs/lib/nimbus-jose-jwt-4.41.1.jar
/usr/share/hadoop/hdfs/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/hdfs/lib/accessors-smart-1.2.jar
/usr/share/hadoop/hdfs/lib/commons-configuration2-2.1.1.jar
/usr/share/hadoop/hdfs/lib/okhttp-2.7.5.jar
/usr/share/hadoop/hdfs/lib/jsr311-api-1.1.1.jar
/usr/share/hadoop/hdfs/lib/woodstox-core-5.0.3.jar
/usr/share/hadoop/hdfs/lib/zookeeper-3.4.13.jar
/usr/share/hadoop/hdfs/lib/kerb-server-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-client-1.0.1.jar
/usr/share/hadoop/hdfs/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/hdfs/lib/audience-annotations-0.5.0.jar
/usr/share/hadoop/hdfs/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/hdfs/lib/protobuf-java-3.6.1.jar
/usr/share/hadoop/hdfs/lib/snappy-java-1.0.5.jar
/usr/share/hadoop/hdfs/lib/re2j-1.1.jar
/usr/share/hadoop/hdfs/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/hdfs/lib/kerby-util-1.0.1.jar
/usr/share/hadoop/hdfs/lib/commons-daemon-1.0.13.jar
/usr/share/hadoop/hdfs/lib/kerb-simplekdc-1.0.1.jar
/usr/share/hadoop/hdfs/lib/jsr305-3.0.0.jar
/usr/share/hadoop/hdfs/lib/htrace-core4-4.1.0-incubating.jar
/usr/share/hadoop/hdfs/lib/jersey-core-1.19.jar
/usr/share/hadoop/hdfs/lib/jersey-json-1.19.jar
/usr/share/hadoop/hdfs/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/hdfs/lib/commons-text-1.4.jar
/usr/share/hadoop/hdfs/lib/okio-1.6.0.jar
/usr/share/hadoop/hdfs/lib/avro-1.7.7.jar
/usr/share/hadoop/hdfs/lib/curator-client-2.12.0.jar
/usr/share/hadoop/hdfs/lib/leveldbjni-all-1.8.jar
/usr/share/hadoop/hdfs/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/hdfs/lib/kerby-config-1.0.1.jar
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0-alpha3.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0-alpha4.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.7.2.xml
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.22.0.xml
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.21.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.2.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.8.2.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.1.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.1.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.3.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.9.1.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.1.1.xml
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.20.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.6.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0-alpha2.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.8.0.xml
/usr/share/hadoop/hdfs/jdiff/Null.java
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.8.3.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0.xml
/usr/share/hadoop/hdfs/hadoop-hdfs-3.2.0-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-httpfs-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-app-3.2.0.jar
/usr/share/hadoop/mapreduce/lib-examples/hsqldb-2.3.4.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-common-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-shuffle-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-3.2.0-tests.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-nativetask-3.2.0.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-jobclient-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-plugins-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-nativetask-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-plugins-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-shuffle-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-examples-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-core-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-common-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-examples-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-app-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-core-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-common-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-jobclient-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-shuffle-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-nativetask-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-app-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-core-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-examples-3.2.0.jar
/usr/share/hadoop/mapreduce/lib/hamcrest-core-1.3.jar
/usr/share/hadoop/mapreduce/lib/junit-4.11.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-uploader-3.2.0.jar
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_3.1.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_3.1.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.8.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.6.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.8.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.7.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.8.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.6.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.8.3.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_3.1.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.8.3.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.8.3.xml
/usr/share/hadoop/mapreduce/jdiff/Null.java
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.8.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.6.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.7.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.8.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.7.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.8.0.xml
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-plugins-3.2.0.jar
/usr/share/defaults/hadoop/workers
/usr/share/defaults/hadoop/kms-log4j.properties
/usr/share/defaults/hadoop/configuration.xsl
/usr/share/defaults/hadoop/httpfs-env.sh
/usr/share/defaults/hadoop/mapred-site.xml
/usr/share/defaults/hadoop/hadoop-metrics2.properties
/usr/share/defaults/hadoop/hadoop-user-functions.sh.example
/usr/share/defaults/hadoop/httpfs-site.xml
/usr/share/defaults/hadoop/log4j.properties
/usr/share/defaults/hadoop/kms-env.sh
/usr/share/defaults/hadoop/yarn-env.sh
/usr/share/defaults/hadoop/ssl-client.xml.example
/usr/share/defaults/hadoop/yarn-site.xml
/usr/share/defaults/hadoop/container-executor.cfg
/usr/share/defaults/hadoop/yarnservice-log4j.properties
/usr/share/defaults/hadoop/core-site.xml
/usr/share/defaults/hadoop/ssl-server.xml.example
/usr/share/defaults/hadoop/user_ec_policies.xml.template
/usr/share/defaults/hadoop/hadoop-env.sh
/usr/share/defaults/hadoop/httpfs-log4j.properties
/usr/share/defaults/hadoop/mapred-env.sh
/usr/share/defaults/hadoop/capacity-scheduler.xml
/usr/share/defaults/hadoop/mapred-queues.xml.template
/usr/share/defaults/hadoop/kms-acls.xml
/usr/share/defaults/hadoop/httpfs-signature.secret
/usr/share/defaults/hadoop/hadoop-policy.xml
/usr/share/defaults/hadoop/kms-site.xml
/usr/share/defaults/hadoop/shellprofile.d/example.sh
/usr/share/defaults/hadoop/hdfs-site.xml
/usr/bin/oom-listener
/usr/bin/yarn
/usr/bin/container-executor
/usr/bin/hadoop
/usr/bin/mapred
/usr/bin/hdfs
/usr/bin/test-container-executor
/usr/sbin/start-balancer.sh
/usr/sbin/hadoop-daemon.sh
/usr/sbin/yarn-daemon.sh
/usr/sbin/stop-dfs.sh
/usr/sbin/httpfs.sh
/usr/sbin/mr-jobhistory-daemon.sh
/usr/sbin/kms.sh
/usr/sbin/start-all.sh
/usr/sbin/hadoop-daemons.sh
/usr/sbin/start-dfs.sh
/usr/sbin/distribute-exclude.sh
/usr/sbin/stop-balancer.sh
/usr/sbin/stop-yarn.sh
/usr/sbin/start-yarn.sh
/usr/sbin/refresh-namenodes.sh
/usr/sbin/yarn-daemons.sh
/usr/sbin/workers.sh
/usr/sbin/stop-all.sh
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreTables.sql
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreUser.sql
/usr/sbin/FederationStateStore/MySQL/dropStoreProcedures.sql
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreStoredProcs.sql
/usr/sbin/FederationStateStore/MySQL/dropDatabase.sql
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreDatabase.sql
/usr/sbin/FederationStateStore/MySQL/dropTables.sql
/usr/sbin/FederationStateStore/MySQL/dropUser.sql
/usr/sbin/FederationStateStore/SQLServer/FederationStateStoreTables.sql
/usr/sbin/FederationStateStore/SQLServer/FederationStateStoreStoreProcs.sql
/usr/sbin/stop-secure-dns.sh
/usr/sbin/start-secure-dns.sh
/usr/lib/debug/usr/lib/native/examples/wordcount-part.debug
/usr/lib/debug/usr/lib/native/examples/wordcount-nopipe.debug
/usr/lib/debug/usr/lib/native/examples/wordcount-simple.debug
/usr/lib/debug/usr/lib/native/examples/pipes-sort.debug
/usr/lib/debug/usr/lib/native/libhadoop.so.1.0.0.debug
/usr/lib/debug/usr/lib/native/libnativetask.so.1.0.0.debug
/usr/lib/debug/usr/bin/container-executor.debug
/usr/lib/debug/usr/bin/oom-listener.debug
/usr/lib/debug/usr/bin/test-container-executor.debug
/usr/lib/native/examples/wordcount-nopipe
/usr/lib/native/examples/wordcount-part
/usr/lib/native/examples/wordcount-simple
/usr/lib/native/examples/pipes-sort
/usr/lib/native/libhadooputils.a
/usr/lib/native/libhadoop.so.1.0.0
/usr/lib/native/libhadoop.so
/usr/lib/native/libnativetask.so.1.0.0
/usr/lib/native/libnativetask.so
/usr/lib/native/libnativetask.a
/usr/lib/native/libhadoop.a
/usr/lib/native/libhadooppipes.a
/usr/libexec/tools/hadoop-archive-logs.sh
/usr/libexec/tools/hadoop-extras.sh
/usr/libexec/tools/hadoop-resourceestimator.sh
/usr/libexec/tools/hadoop-gridmix.sh
/usr/libexec/tools/hadoop-distcp.sh
/usr/libexec/tools/hadoop-sls.sh
/usr/libexec/tools/hadoop-aws.sh
/usr/libexec/tools/hadoop-archives.sh
/usr/libexec/tools/hadoop-streaming.sh
/usr/libexec/tools/hadoop-rumen.sh
/usr/libexec/hadoop-layout.sh.example
/usr/libexec/mapred-config.sh
/usr/libexec/hadoop-config.sh
/usr/libexec/yarn-config.sh
/usr/libexec/shellprofile.d/hadoop-azure-datalake.sh
/usr/libexec/shellprofile.d/hadoop-s3guard.sh
/usr/libexec/shellprofile.d/hadoop-archive-logs.sh
/usr/libexec/shellprofile.d/hadoop-extras.sh
/usr/libexec/shellprofile.d/hadoop-openstack.sh
/usr/libexec/shellprofile.d/hadoop-azure.sh
/usr/libexec/shellprofile.d/hadoop-kafka.sh
/usr/libexec/shellprofile.d/hadoop-gridmix.sh
/usr/libexec/shellprofile.d/hadoop-distcp.sh
/usr/libexec/shellprofile.d/hadoop-kms.sh
/usr/libexec/shellprofile.d/hadoop-mapreduce.sh
/usr/libexec/shellprofile.d/hadoop-hdfs.sh
/usr/libexec/shellprofile.d/hadoop-aliyun.sh
/usr/libexec/shellprofile.d/hadoop-yarn.sh
/usr/libexec/shellprofile.d/hadoop-aws.sh
/usr/libexec/shellprofile.d/hadoop-archives.sh
/usr/libexec/shellprofile.d/hadoop-httpfs.sh
/usr/libexec/shellprofile.d/hadoop-streaming.sh
/usr/libexec/shellprofile.d/hadoop-rumen.sh
/usr/libexec/hadoop-functions.sh
/usr/libexec/hdfs-config.sh
