#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : apache-hadoop
Version  : 3.2.0
Release  : 32
URL      : http://apache.cs.utah.edu/hadoop/common/hadoop-3.2.0/hadoop-3.2.0-src.tar.gz
Source0  : http://apache.cs.utah.edu/hadoop/common/hadoop-3.2.0/hadoop-3.2.0-src.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 MIT
Requires: apache-hadoop-bin = %{version}-%{release}
Requires: apache-hadoop-data = %{version}-%{release}
Requires: apache-hadoop-lib = %{version}-%{release}
Requires: apache-hadoop-libexec = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-cmake
BuildRequires : buildreq-mvn
BuildRequires : cyrus-sasl
BuildRequires : cyrus-sasl-dev
BuildRequires : mvn(antlr:antlr:jar) = 2.7.2
BuildRequires : mvn(avalon-framework:avalon-framework:jar) = 4.1.3
BuildRequires : mvn(backport-util-concurrent:backport-util-concurrent:jar) = 3.1
BuildRequires : mvn(biz.aQute.bnd:bndlib:jar) = 2.3.0
BuildRequires : mvn(cglib:cglib:jar) = 3.2.0
BuildRequires : mvn(ch.qos.logback:logback-classic:jar) = 1.1.2
BuildRequires : mvn(ch.qos.logback:logback-parent:pom) = 1.1.2
BuildRequires : mvn(classworlds:classworlds:jar) = 1.1
BuildRequires : mvn(classworlds:classworlds:jar) = 1.1.alpha.2
BuildRequires : mvn(com.aliyun.oss:aliyun-sdk-oss:jar) = 2.8.3
BuildRequires : mvn(com.amazonaws:aws-java-sdk-bundle:jar) = 1.11.375
BuildRequires : mvn(com.cedarsoftware:java-util:jar) = 1.9.0
BuildRequires : mvn(com.cedarsoftware:json-io:jar) = 2.5.1
BuildRequires : mvn(com.eclipsesource.minimal-json:minimal-json:jar) = 0.9.1
BuildRequires : mvn(com.fasterxml.jackson.core:jackson-annotations:jar) = 2.9.5
BuildRequires : mvn(com.fasterxml.jackson.core:jackson-core:jar) = 2.9.5
BuildRequires : mvn(com.fasterxml.jackson.core:jackson-databind:jar) = 2.9.5
BuildRequires : mvn(com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar) = 2.9.5
BuildRequires : mvn(com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar) = 2.9.5
BuildRequires : mvn(com.fasterxml.jackson.module:jackson-modules-base:pom) = 2.9.5
BuildRequires : mvn(com.fasterxml.jackson:jackson-base:pom) = 2.9.5
BuildRequires : mvn(com.fasterxml.jackson:jackson-parent:pom) = 2.9.1
BuildRequires : mvn(com.fasterxml.woodstox:woodstox-core:jar) = 5.0.3
BuildRequires : mvn(com.github.stephenc.findbugs:findbugs-annotations:jar) = 1.3.9.1
BuildRequires : mvn(com.github.stephenc.jcip:jcip-annotations:jar) = 1.0.1
BuildRequires : mvn(com.google.code.gson:gson:jar) = 2.2.4
BuildRequires : mvn(com.google.collections:google-collections:jar) = 1.0
BuildRequires : mvn(com.google.inject.extensions:guice-servlet:jar) = 4.0
BuildRequires : mvn(com.google.protobuf:protobuf-java:jar) = 3.6.1
BuildRequires : mvn(com.google.re2j:re2j:jar) = 1.1
BuildRequires : mvn(com.google:google:pom) = 1
BuildRequires : mvn(com.googlecode.json-simple:json-simple:jar) = 1.1.1
BuildRequires : mvn(com.ibm.icu:icu4j:jar) = 58.1
BuildRequires : mvn(com.jamesmurty.utils:java-xmlbuilder:jar) = 0.4
BuildRequires : mvn(com.jcraft:jsch:jar) = 0.1.44.1
BuildRequires : mvn(com.lmax:disruptor:jar) = 3.3.0
BuildRequires : mvn(com.microsoft.azure:azure-data-lake-store-sdk:jar) = 2.2.9
BuildRequires : mvn(com.microsoft.azure:azure-keyvault-core:jar) = 1.0.0
BuildRequires : mvn(com.microsoft.azure:azure-storage:jar) = 7.0.0
BuildRequires : mvn(com.microsoft.sqlserver:mssql-jdbc:jar) = 6.2.1.jre7
BuildRequires : mvn(com.nimbusds:nimbus-jose-jwt:jar) = 4.41.1
BuildRequires : mvn(com.openhtmltopdf:openhtmltopdf-core:jar) = 0.0.1.RC9
BuildRequires : mvn(com.openhtmltopdf:openhtmltopdf-jsoup-dom-converter:jar) = 0.0.1.RC9
BuildRequires : mvn(com.openhtmltopdf:openhtmltopdf-pdfbox:jar) = 0.0.1.RC9
BuildRequires : mvn(com.openhtmltopdf:openhtmltopdf-rtl-support:jar) = 0.0.1.RC9
BuildRequires : mvn(com.squareup.okhttp3:mockwebserver:jar) = 3.7.0
BuildRequires : mvn(com.squareup.okio:okio:jar) = 1.12.0
BuildRequires : mvn(com.sun.jersey:jersey-core:jar) = 1.19
BuildRequires : mvn(com.sun.jersey:jersey-json:jar) = 1.19
BuildRequires : mvn(com.sun.jersey:jersey-server:jar) = 1.19
BuildRequires : mvn(com.sun.jersey:jersey-servlet:jar) = 1.19
BuildRequires : mvn(com.sun.xml.bind:jaxb-impl:jar) = 2.2.3.1
BuildRequires : mvn(com.thoughtworks.paranamer:paranamer:jar) = 2.3
BuildRequires : mvn(com.thoughtworks.qdox:qdox:jar) = 2.0.M7
BuildRequires : mvn(com.thoughtworks.xstream:xstream:jar) = 1.4.9
BuildRequires : mvn(com.vladsch.flexmark:flexmark-all:jar) = 0.18.4
BuildRequires : mvn(com.zaxxer:HikariCP-java7:jar) = 2.4.12
BuildRequires : mvn(commons-beanutils:commons-beanutils:jar) = 1.7.0
BuildRequires : mvn(commons-chain:commons-chain:jar) = 1.1
BuildRequires : mvn(commons-collections:commons-collections:jar) = 3.2
BuildRequires : mvn(commons-configuration:commons-configuration:jar) = 1.6
BuildRequires : mvn(commons-daemon:commons-daemon:jar) = 1.0.13
BuildRequires : mvn(commons-digester:commons-digester:jar) = 1.8
BuildRequires : mvn(commons-el:commons-el:jar) = 1.0
BuildRequires : mvn(commons-httpclient:commons-httpclient:jar) = 3.1
BuildRequires : mvn(commons-net:commons-net:jar) = 3.6
BuildRequires : mvn(commons-pool:commons-pool:jar) = 1.6
BuildRequires : mvn(commons-validator:commons-validator:jar) = 1.3.1
BuildRequires : mvn(de.ruedigermoeller:fst:jar) = 2.50
BuildRequires : mvn(dnsjava:dnsjava:jar) = 2.1.7
BuildRequires : mvn(dom4j:dom4j:jar) = 1.1
BuildRequires : mvn(io.dropwizard.metrics:metrics-core:jar) = 3.2.4
BuildRequires : mvn(io.netty:netty:jar) = 3.10.5.Final
BuildRequires : mvn(io.swagger:swagger-annotations:jar) = 1.5.4
BuildRequires : mvn(javax.activation:javax.activation-api:jar) = 1.2.0
BuildRequires : mvn(javax.servlet.jsp:jsp-api:jar) = 2.1
BuildRequires : mvn(javax.servlet:javax.servlet-api:jar) = 3.1.0
BuildRequires : mvn(javax.servlet:servlet-api:jar) = 2.5
BuildRequires : mvn(javax.ws.rs:jsr311-api:jar) = 1.1.1
BuildRequires : mvn(javax.xml.bind:jaxb-api:jar) = 2.2.11
BuildRequires : mvn(jdiff:jdiff:jar) = 1.0.9
BuildRequires : mvn(junit:junit:jar) = 3.8.1
BuildRequires : mvn(ldapsdk:ldapsdk:jar) = 4.1
BuildRequires : mvn(log4j:log4j:jar) = 1.2.12
BuildRequires : mvn(logkit:logkit:jar) = 1.0.1
BuildRequires : mvn(net.java.dev.jets3t:jets3t:jar) = 0.9.0
BuildRequires : mvn(net.jpountz.lz4:lz4:jar) = 1.2.0
BuildRequires : mvn(net.minidev:accessors-smart:jar) = 1.2
BuildRequires : mvn(net.minidev:json-smart:jar) = 2.3
BuildRequires : mvn(net.sf.ehcache:ehcache:jar) = 2.8.5
BuildRequires : mvn(net.sf.jtidy:jtidy:jar) = r938
BuildRequires : mvn(net.sf.kosmosfs:kfs:jar) = 0.3
BuildRequires : mvn(org.apache.ant:ant-launcher:jar) = 1.8.2
BuildRequires : mvn(org.apache.ant:ant:jar) = 1.8.2
BuildRequires : mvn(org.apache.avro:avro-maven-plugin:jar) = 1.7.7
BuildRequires : mvn(org.apache.commons:commons-compress:jar) = 1.11
BuildRequires : mvn(org.apache.commons:commons-configuration2:jar) = 2.1.1
BuildRequires : mvn(org.apache.commons:commons-csv:jar) = 1.0
BuildRequires : mvn(org.apache.commons:commons-exec:jar) = 1.2
BuildRequires : mvn(org.apache.commons:commons-math3:jar) = 3.1.1
BuildRequires : mvn(org.apache.commons:commons-math:jar) = 2.2
BuildRequires : mvn(org.apache.commons:commons-parent:pom) = 41
BuildRequires : mvn(org.apache.commons:commons-text:jar) = 1.4
BuildRequires : mvn(org.apache.curator:curator-framework:jar) = 2.12.0
BuildRequires : mvn(org.apache.curator:curator-test:jar) = 2.12.0
BuildRequires : mvn(org.apache.directory.api:api-ldap-codec-core:jar) = 1.0.0.M33
BuildRequires : mvn(org.apache.directory.api:api-ldap-model:jar) = 1.0.0.M33
BuildRequires : mvn(org.apache.directory.jdbm:apacheds-jdbm1:jar) = 2.0.0.M3
BuildRequires : mvn(org.apache.directory.mavibot:mavibot:jar) = 1.0.0.M8
BuildRequires : mvn(org.apache.directory.project:project:pom) = 35
BuildRequires : mvn(org.apache.directory.server:apacheds-core-integ:jar) = 2.0.0.M21
BuildRequires : mvn(org.apache.directory.server:apacheds-core:jar) = 2.0.0.M21
BuildRequires : mvn(org.apache.directory.server:apacheds-ldif-partition:jar) = 2.0.0.M21
BuildRequires : mvn(org.apache.directory.server:apacheds-protocol-ldap:jar) = 2.0.0.M21
BuildRequires : mvn(org.apache.directory.server:apacheds-server-integ:jar) = 2.0.0.M21
BuildRequires : mvn(org.apache.felix:felix-parent:pom) = 2.1
BuildRequires : mvn(org.apache.felix:maven-bundle-plugin:jar) = 2.5.0
BuildRequires : mvn(org.apache.felix:org.apache.felix.bundlerepository:jar) = 1.6.6
BuildRequires : mvn(org.apache.geronimo.genesis:genesis-java5-flava:pom) = 2.0
BuildRequires : mvn(org.apache.geronimo.specs:geronimo-jcache_1.0_spec:jar) = 1.0.alpha.1
BuildRequires : mvn(org.apache.hadoop:hadoop-auth:jar) = 2.5.1
BuildRequires : mvn(org.apache.hadoop:hadoop-common:jar) = 2.5.1
BuildRequires : mvn(org.apache.hadoop:hadoop-common:jar:tests) = 2.5.1
BuildRequires : mvn(org.apache.hadoop:hadoop-hdfs:jar) = 2.5.1
BuildRequires : mvn(org.apache.hadoop:hadoop-hdfs:jar:tests) = 2.5.1
BuildRequires : mvn(org.apache.hbase:hbase-common:jar) = 1.2.6
BuildRequires : mvn(org.apache.htrace:htrace-core4:jar) = 4.1.0.incubating
BuildRequires : mvn(org.apache.kafka:kafka-clients:jar) = 0.8.2.1
BuildRequires : mvn(org.apache.kerby:kerb-simplekdc:jar) = 1.0.1
BuildRequires : mvn(org.apache.maven.doxia:doxia-sink-api:jar) = 1.0
BuildRequires : mvn(org.apache.maven.doxia:doxia-site-renderer:jar) = 1.0
BuildRequires : mvn(org.apache.maven.plugins:maven-antrun-plugin:jar) = 1.7
BuildRequires : mvn(org.apache.maven.plugins:maven-assembly-plugin:jar) = 2.4
BuildRequires : mvn(org.apache.maven.plugins:maven-compiler-plugin:jar) = 3.1
BuildRequires : mvn(org.apache.maven.plugins:maven-enforcer-plugin:jar) = 3.0.0.M1
BuildRequires : mvn(org.apache.maven.plugins:maven-jar-plugin:jar) = 2.4
BuildRequires : mvn(org.apache.maven.plugins:maven-javadoc-plugin:jar) = 3.0.1
BuildRequires : mvn(org.apache.maven.plugins:maven-plugins:pom) = 30
BuildRequires : mvn(org.apache.maven.plugins:maven-remote-resources-plugin:jar) = 1.5
BuildRequires : mvn(org.apache.maven.plugins:maven-resources-plugin:jar) = 3.0.1
BuildRequires : mvn(org.apache.maven.plugins:maven-shade-plugin:jar) = 3.2.1
BuildRequires : mvn(org.apache.maven.plugins:maven-site-plugin:jar) = 3.6
BuildRequires : mvn(org.apache.maven.plugins:maven-source-plugin:jar) = 2.3
BuildRequires : mvn(org.apache.maven.plugins:maven-surefire-plugin:jar) = 2.12.4
BuildRequires : mvn(org.apache.maven.plugins:maven-war-plugin:jar) = 3.1.0
BuildRequires : mvn(org.apache.maven.reporting:maven-reporting-api:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven.reporting:maven-reporting-api:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven.reporting:maven-reporting-exec:jar) = 1.3
BuildRequires : mvn(org.apache.maven.reporting:maven-reporting-impl:jar) = 2.1
BuildRequires : mvn(org.apache.maven.reporting:maven-reporting-impl:jar) = 2.3
BuildRequires : mvn(org.apache.maven.shared:file-management:jar) = 1.1
BuildRequires : mvn(org.apache.maven.shared:maven-artifact-transfer:jar) = 0.9.1
BuildRequires : mvn(org.apache.maven.shared:maven-common-artifact-filters:jar) = 3.0.1
BuildRequires : mvn(org.apache.maven.shared:maven-dependency-tree:jar) = 2.1
BuildRequires : mvn(org.apache.maven.shared:maven-filtering:jar) = 3.1.1
BuildRequires : mvn(org.apache.maven.shared:maven-invoker:jar) = 3.0.0
BuildRequires : mvn(org.apache.maven.shared:maven-mapping:jar) = 3.0.0
BuildRequires : mvn(org.apache.maven.shared:maven-repository-builder:jar) = 1.0.alpha.2
BuildRequires : mvn(org.apache.maven:maven-aether-provider:jar) = 3.0
BuildRequires : mvn(org.apache.maven:maven-archiver:jar) = 2.5
BuildRequires : mvn(org.apache.maven:maven-artifact-manager:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-artifact-manager:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-artifact:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-artifact:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-compat:jar) = 3.0
BuildRequires : mvn(org.apache.maven:maven-core:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-error-diagnostics:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-error-diagnostics:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-model-builder:jar) = 3.0
BuildRequires : mvn(org.apache.maven:maven-model:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-model:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-monitor:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-monitor:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-parent:pom) = 5
BuildRequires : mvn(org.apache.maven:maven-plugin-api:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-plugin-api:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-plugin-descriptor:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-plugin-descriptor:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-plugin-parameter-documenter:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-plugin-parameter-documenter:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-plugin-registry:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-plugin-registry:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-plugin-registry:jar) = 2.2.0
BuildRequires : mvn(org.apache.maven:maven-profile:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-profile:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-project:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-project:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-project:jar) = 2.2.0
BuildRequires : mvn(org.apache.maven:maven-repository-metadata:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-repository-metadata:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-settings-builder:jar) = 3.0
BuildRequires : mvn(org.apache.maven:maven-settings:jar) = 2.0.6
BuildRequires : mvn(org.apache.maven:maven-settings:jar) = 2.0.7
BuildRequires : mvn(org.apache.maven:maven-toolchain:jar) = 1.0
BuildRequires : mvn(org.apache.maven:maven:pom) = 2.0.7
BuildRequires : mvn(org.apache.mina:mina-core:jar) = 2.0.16
BuildRequires : mvn(org.apache.pdfbox:pdfbox:jar) = 2.0.4
BuildRequires : mvn(org.apache.servicemix.bundles:org.apache.servicemix.bundles.antlr:jar) = 2.7.7_5
BuildRequires : mvn(org.apache.servicemix.bundles:org.apache.servicemix.bundles.dom4j:jar) = 1.6.1_5
BuildRequires : mvn(org.apache.servicemix.bundles:org.apache.servicemix.bundles.xpp3:jar) = 1.1.4c_6
BuildRequires : mvn(org.apache.servicemix:servicemix-pom:pom) = 5
BuildRequires : mvn(org.apache.sshd:sshd-core:jar) = 1.6.0
BuildRequires : mvn(org.apache.struts:struts-core:jar) = 1.3.8
BuildRequires : mvn(org.apache.struts:struts-taglib:jar) = 1.3.8
BuildRequires : mvn(org.apache.struts:struts-tiles:jar) = 1.3.8
BuildRequires : mvn(org.apache.velocity:velocity-tools:jar) = 2.0
BuildRequires : mvn(org.apache.velocity:velocity:jar) = 1.5
BuildRequires : mvn(org.apache.xbean:xbean-reflect:jar) = 3.7
BuildRequires : mvn(org.apache.yetus:audience-annotations:jar) = 0.5.0
BuildRequires : mvn(org.apache.zookeeper:zookeeper:jar) = 3.4.13
BuildRequires : mvn(org.apache:apache:pom) = 9
BuildRequires : mvn(org.assertj:assertj-core:jar) = 3.8.0
BuildRequires : mvn(org.assertj:assertj-parent-pom:pom) = 2.1.6
BuildRequires : mvn(org.beanshell:bsh:jar) = 2.0b4
BuildRequires : mvn(org.bouncycastle:bcprov-jdk15on:jar) = 1.52
BuildRequires : mvn(org.codehaus.jackson:jackson-core-asl:jar) = 1.9.13
BuildRequires : mvn(org.codehaus.jackson:jackson-mapper-asl:jar) = 1.9.13
BuildRequires : mvn(org.codehaus.jettison:jettison:jar) = 1.1
BuildRequires : mvn(org.codehaus.mojo:exec-maven-plugin:jar) = 1.3.1
BuildRequires : mvn(org.codehaus.mojo:extra-enforcer-rules:jar) = 1.0.beta.3
BuildRequires : mvn(org.codehaus.mojo:license-maven-plugin:jar) = 1.10
BuildRequires : mvn(org.codehaus.mojo:mojo-parent:pom) = 33
BuildRequires : mvn(org.codehaus.plexus:plexus-archiver:jar) = 2.1
BuildRequires : mvn(org.codehaus.plexus:plexus-compiler-api:jar) = 2.2
BuildRequires : mvn(org.codehaus.plexus:plexus-compiler-javac:jar) = 2.2
BuildRequires : mvn(org.codehaus.plexus:plexus-compiler-manager:jar) = 2.2
BuildRequires : mvn(org.codehaus.plexus:plexus-i18n:jar) = 1.0.beta.7
BuildRequires : mvn(org.codehaus.plexus:plexus-interactivity-api:jar) = 1.0.alpha.4
BuildRequires : mvn(org.codehaus.plexus:plexus-io:jar) = 2.0.2
BuildRequires : mvn(org.codehaus.plexus:plexus-java:jar) = 0.9.8
BuildRequires : mvn(org.codehaus.plexus:plexus-resources:jar) = 1.0.alpha.7
BuildRequires : mvn(org.codehaus.plexus:plexus-velocity:jar) = 1.1.7
BuildRequires : mvn(org.codehaus.plexus:plexus:pom) = 3.3
BuildRequires : mvn(org.codehaus.woodstox:stax2-api:jar) = 3.1.4
BuildRequires : mvn(org.easymock:easymock:jar) = 2.4
BuildRequires : mvn(org.freemarker:freemarker:jar) = 2.3.20
BuildRequires : mvn(org.fusesource.leveldbjni:leveldbjni-all:jar) = 1.8
BuildRequires : mvn(org.fusesource:fusesource-pom:pom) = 1.9
BuildRequires : mvn(org.glassfish.grizzly:grizzly-http-server:jar) = 2.2.21
BuildRequires : mvn(org.glassfish.grizzly:grizzly-http-servlet:jar) = 2.2.21
BuildRequires : mvn(org.glassfish.grizzly:grizzly-http:jar) = 2.2.21
BuildRequires : mvn(org.hamcrest:hamcrest-core:jar) = 1.3
BuildRequires : mvn(org.hsqldb:hsqldb:jar) = 2.3.4
BuildRequires : mvn(org.iq80.snappy:snappy:jar) = 0.4
BuildRequires : mvn(org.jamon:jamon-java-parent:pom) = 2.4.1
BuildRequires : mvn(org.jamon:jamon-parent:pom) = 2.4.1
BuildRequires : mvn(org.jamon:jamon-runtime:jar) = 2.4.1
BuildRequires : mvn(org.javassist:javassist:jar) = 3.18.1.GA
BuildRequires : mvn(org.jboss:jboss-parent:pom) = 21
BuildRequires : mvn(org.jdom:jdom2:jar) = 2.0.6
BuildRequires : mvn(org.jdom:jdom:jar) = 1.1
BuildRequires : mvn(org.jruby.jcodings:jcodings:jar) = 1.0.13
BuildRequires : mvn(org.jruby.joni:joni:jar) = 2.1.2
BuildRequires : mvn(org.json:json:jar) = 20090211
BuildRequires : mvn(org.mock-server:mockserver-netty:jar) = 3.9.2
BuildRequires : mvn(org.mockito:mockito-all:jar) = 1.8.5
BuildRequires : mvn(org.mortbay.jetty:jetty-parent:pom) = 10
BuildRequires : mvn(org.mortbay.jetty:jetty-util:jar) = 6.1.25
BuildRequires : mvn(org.mortbay.jetty:jetty:jar) = 6.1.25
BuildRequires : mvn(org.mortbay.jetty:servlet-api:jar) = 2.5.20081211
BuildRequires : mvn(org.nibor.autolink:autolink:jar) = 0.6.0
BuildRequires : mvn(org.nuiton.processor:nuiton-processor:jar) = 1.3
BuildRequires : mvn(org.objenesis:objenesis:jar) = 2.6
BuildRequires : mvn(org.ojalgo:ojalgo:jar) = 43.0
BuildRequires : mvn(org.osgi:org.osgi.compendium:jar) = 4.2.0
BuildRequires : mvn(org.osgi:org.osgi.core:jar) = 4.1.0
BuildRequires : mvn(org.ow2.asm:asm:jar) = 6.1.1
BuildRequires : mvn(org.ow2:ow2:pom) = 1.5
BuildRequires : mvn(org.skyscreamer:jsonassert:jar) = 1.3.0
BuildRequires : mvn(org.sonatype.aether:aether-api:jar) = 1.7
BuildRequires : mvn(org.sonatype.aether:aether-impl:jar) = 1.7
BuildRequires : mvn(org.sonatype.aether:aether-util:jar) = 1.7
BuildRequires : mvn(org.sonatype.plexus:plexus-build-api:jar) = 0.0.7
BuildRequires : mvn(org.sonatype.sisu:sisu-guice:jar:noaop) = 2.1.7
BuildRequires : mvn(org.sonatype.spice:spice-parent:pom) = 16
BuildRequires : mvn(org.tukaani:xz:jar) = 1.5
BuildRequires : mvn(org.vafer:jdependency:jar) = 2.1.1
BuildRequires : mvn(org.wildfly.openssl:wildfly-openssl:jar) = 1.0.4.Final
BuildRequires : mvn(org.xerial.snappy:snappy-java:jar) = 1.0.5
BuildRequires : mvn(org.yaml:snakeyaml:jar) = 1.16
BuildRequires : mvn(oro:oro:jar) = 2.0.8
BuildRequires : mvn(sslext:sslext:jar) = 1.2.0
BuildRequires : mvn(tomcat:jasper-compiler:jar) = 5.5.23
BuildRequires : mvn(tomcat:jasper-runtime:jar) = 5.5.23
BuildRequires : mvn(xerces:xercesImpl:jar) = 2.9.1
BuildRequires : mvn(xml-apis:xml-apis:jar) = 1.0.b2
BuildRequires : mvn(xmlenc:xmlenc:jar) = 0.52
BuildRequires : mvn(xmlpull:xmlpull:jar) = 1.1.3.1
BuildRequires : mvn(xmlunit:xmlunit:jar) = 1.5
BuildRequires : mvn(xpp3:xpp3_min:jar) = 1.1.4c
BuildRequires : mvn-aether-core
BuildRequires : mvn-aopalliance
BuildRequires : mvn-cdi-api
BuildRequires : mvn-commons-cli
BuildRequires : mvn-commons-codec
BuildRequires : mvn-commons-io
BuildRequires : mvn-commons-lang
BuildRequires : mvn-commons-lang3
BuildRequires : mvn-commons-logging
BuildRequires : mvn-guava
BuildRequires : mvn-guice
BuildRequires : mvn-httpcomponents-client
BuildRequires : mvn-httpcomponents-core
BuildRequires : mvn-jsoup
BuildRequires : mvn-jsr305
BuildRequires : mvn-plexus-cipher
BuildRequires : mvn-plexus-classworlds
BuildRequires : mvn-plexus-containers
BuildRequires : mvn-plexus-interpolation
BuildRequires : mvn-plexus-utils
BuildRequires : mvn-sisu
BuildRequires : mvn-slf4j
BuildRequires : mvn-sonatype-plexus-sec-dispatcher
BuildRequires : mvn-wagon
BuildRequires : openjdk11
BuildRequires : openjdk11-dev
BuildRequires : openssl-dev
BuildRequires : protobuf
BuildRequires : protobuf-dev
BuildRequires : zlib-dev
Patch1: 0001-Integrate-JDK11.patch
Patch2: 0001-Java_home-on-CLR.patch
Patch3: HADOOP-11364.01.patch
Patch4: 0001-Stateless-v2.patch
Patch5: 0001-Change-protobuf-version.patch
Patch6: protobuf3.patch
Patch7: protobuf-3.6.1-hadoop-3.2.0-On-CLR.patch
Patch8: 0001-YARN-8498.-Yarn-NodeManager-OOM-Listener-Fails-Compi.patch

%description
YARN (YET ANOTHER RESOURCE NEGOTIATOR or YARN Application Resource Negotiator)
------------------------------------------------------------------------------

%package bin
Summary: bin components for the apache-hadoop package.
Group: Binaries
Requires: apache-hadoop-data = %{version}-%{release}
Requires: apache-hadoop-libexec = %{version}-%{release}

%description bin
bin components for the apache-hadoop package.


%package data
Summary: data components for the apache-hadoop package.
Group: Data

%description data
data components for the apache-hadoop package.


%package dev
Summary: dev components for the apache-hadoop package.
Group: Development
Requires: apache-hadoop-lib = %{version}-%{release}
Requires: apache-hadoop-bin = %{version}-%{release}
Requires: apache-hadoop-data = %{version}-%{release}
Provides: apache-hadoop-devel = %{version}-%{release}
Requires: apache-hadoop = %{version}-%{release}

%description dev
dev components for the apache-hadoop package.


%package doc
Summary: doc components for the apache-hadoop package.
Group: Documentation

%description doc
doc components for the apache-hadoop package.


%package lib
Summary: lib components for the apache-hadoop package.
Group: Libraries
Requires: apache-hadoop-data = %{version}-%{release}
Requires: apache-hadoop-libexec = %{version}-%{release}

%description lib
lib components for the apache-hadoop package.


%package libexec
Summary: libexec components for the apache-hadoop package.
Group: Default

%description libexec
libexec components for the apache-hadoop package.


%prep
%setup -q -n hadoop-3.2.0-src
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1

%build
## build_prepend content
export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
mkdir -p %{buildroot}
mkdir -p ~/.m2
cp -r /usr/share/java/.m2/* ~/.m2/ || :
mvn --offline package package -fae -o -Pnative -Pdist -DskipTests -Dtar -Danimal.sniffer.skip=true -Dmaven.javadoc.skip=true -Djavac.version=11 -Dguava.version=19.0 -Dmaven.plugin-tools.version=3.6.0

%install
## install_prepend content
rm -rf ./hadoop-hdfs-project/hadoop-hdfs-native-client/target/target
rm -r ./hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-nodemanager/target/native/target
rm -rf ./hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-nativetask/target/native/target
rm -rf ./hadoop-common-project/hadoop-common/target/native/target
## install_prepend end

mkdir -p %{buildroot}/usr/share/package-licenses/apache-hadoop
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-hadoop/LICENSE.txt
cp hadoop-common-project/hadoop-common/src/main/native/COPYING %{buildroot}/usr/share/package-licenses/apache-hadoop/hadoop-common-project_hadoop-common_src_main_native_COPYING
cp hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/third_party/asio-1.10.2/COPYING %{buildroot}/usr/share/package-licenses/apache-hadoop/hadoop-hdfs-project_hadoop-hdfs-native-client_src_main_native_libhdfspp_third_party_asio-1.10.2_COPYING
cp hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/third_party/gmock-1.7.0/LICENSE %{buildroot}/usr/share/package-licenses/apache-hadoop/hadoop-hdfs-project_hadoop-hdfs-native-client_src_main_native_libhdfspp_third_party_gmock-1.7.0_LICENSE
cp hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/third_party/rapidxml-1.13/rapidxml/license.txt %{buildroot}/usr/share/package-licenses/apache-hadoop/hadoop-hdfs-project_hadoop-hdfs-native-client_src_main_native_libhdfspp_third_party_rapidxml-1.13_rapidxml_license.txt
cp hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/third_party/uriparser2/uriparser2/LICENSE %{buildroot}/usr/share/package-licenses/apache-hadoop/hadoop-hdfs-project_hadoop-hdfs-native-client_src_main_native_libhdfspp_third_party_uriparser2_uriparser2_LICENSE
cp hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/third_party/uriparser2/uriparser2/uriparser/COPYING %{buildroot}/usr/share/package-licenses/apache-hadoop/hadoop-hdfs-project_hadoop-hdfs-native-client_src_main_native_libhdfspp_third_party_uriparser2_uriparser2_uriparser_COPYING
cp hadoop-tools/hadoop-sls/src/main/html/js/thirdparty/d3-LICENSE %{buildroot}/usr/share/package-licenses/apache-hadoop/hadoop-tools_hadoop-sls_src_main_html_js_thirdparty_d3-LICENSE
for targetdir in $(find . -type d -name target); do
pushd $targetdir
export GROUP_PATH=$(xml sel -t -v '/_:project/_:groupId' -v '/_:project/_:parent/_:groupId' ../pom.xml | sed 's#\.#/#g' | head -1)
export ARTIFACT_ID=$(xml sel -t -v '/_:project/_:artifactId' ../pom.xml | head -1)
export VERSION=$(xml sel -t -v '/_:project/_:version' -v '/_:project/_:parent/_:version' ../pom.xml | head -1)
export DEPLOY_PATH=%{buildroot}/usr/share/java/.m2/repository/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}
mkdir -p ${DEPLOY_PATH}
shopt -s nullglob
for jarfile in ${ARTIFACT_ID}*.jar; do
cp -p "${jarfile}" ${DEPLOY_PATH}/
done
rm -f ${DEPLOY_PATH}/${ARTIFACT_ID}-${VERSION}-sources.jar
cp -p ../pom.xml ${DEPLOY_PATH}/${ARTIFACT_ID}-${VERSION}.pom
popd
done
## install_append content
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/defaults/hadoop
mkdir -p %{buildroot}/usr/share/doc/hadoop
tar -xf hadoop-dist/target/hadoop-*.tar.gz -C %{buildroot}/usr --strip-components=1
mv %{buildroot}/usr/*.txt %{buildroot}/usr/share/doc/hadoop
mv %{buildroot}/usr/etc/* %{buildroot}/usr/share/defaults
find %{buildroot}/usr -iname *.cmd -delete
find %{buildroot}/usr -iname *.orig -delete
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/native/examples/pipes-sort
/usr/lib/native/examples/wordcount-nopipe
/usr/lib/native/examples/wordcount-part
/usr/lib/native/examples/wordcount-simple
/usr/lib/native/libhadoop.a
/usr/lib/native/libhadooppipes.a
/usr/lib/native/libhadooputils.a
/usr/lib/native/libnativetask.a

%files bin
%defattr(-,root,root,-)
/usr/bin/container-executor
/usr/bin/hadoop
/usr/bin/hadoop-functions.sh.orig
/usr/bin/hadoop.cmd
/usr/bin/hdfs
/usr/bin/hdfs.cmd
/usr/bin/mapred
/usr/bin/mapred.cmd
/usr/bin/oom-listener
/usr/bin/test-container-executor
/usr/bin/yarn
/usr/bin/yarn.cmd
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreDatabase.sql
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreStoredProcs.sql
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreTables.sql
/usr/sbin/FederationStateStore/MySQL/FederationStateStoreUser.sql
/usr/sbin/FederationStateStore/MySQL/dropDatabase.sql
/usr/sbin/FederationStateStore/MySQL/dropStoreProcedures.sql
/usr/sbin/FederationStateStore/MySQL/dropTables.sql
/usr/sbin/FederationStateStore/MySQL/dropUser.sql
/usr/sbin/FederationStateStore/SQLServer/FederationStateStoreStoreProcs.sql
/usr/sbin/FederationStateStore/SQLServer/FederationStateStoreTables.sql
/usr/sbin/distribute-exclude.sh
/usr/sbin/hadoop-daemon.sh
/usr/sbin/hadoop-daemons.sh
/usr/sbin/httpfs.sh
/usr/sbin/kms.sh
/usr/sbin/mr-jobhistory-daemon.sh
/usr/sbin/refresh-namenodes.sh
/usr/sbin/start-all.cmd
/usr/sbin/start-all.sh
/usr/sbin/start-balancer.sh
/usr/sbin/start-dfs.cmd
/usr/sbin/start-dfs.sh
/usr/sbin/start-secure-dns.sh
/usr/sbin/start-yarn.cmd
/usr/sbin/start-yarn.sh
/usr/sbin/stop-all.cmd
/usr/sbin/stop-all.sh
/usr/sbin/stop-balancer.sh
/usr/sbin/stop-dfs.cmd
/usr/sbin/stop-dfs.sh
/usr/sbin/stop-secure-dns.sh
/usr/sbin/stop-yarn.cmd
/usr/sbin/stop-yarn.sh
/usr/sbin/workers.sh
/usr/sbin/yarn-daemon.sh
/usr/sbin/yarn-daemons.sh

%files data
%defattr(-,root,root,-)
/usr/share/defaults/hadoop/capacity-scheduler.xml
/usr/share/defaults/hadoop/configuration.xsl
/usr/share/defaults/hadoop/container-executor.cfg
/usr/share/defaults/hadoop/core-site.xml
/usr/share/defaults/hadoop/hadoop-env.cmd
/usr/share/defaults/hadoop/hadoop-env.sh
/usr/share/defaults/hadoop/hadoop-metrics2.properties
/usr/share/defaults/hadoop/hadoop-policy.xml
/usr/share/defaults/hadoop/hadoop-user-functions.sh.example
/usr/share/defaults/hadoop/hdfs-site.xml
/usr/share/defaults/hadoop/httpfs-env.sh
/usr/share/defaults/hadoop/httpfs-log4j.properties
/usr/share/defaults/hadoop/httpfs-signature.secret
/usr/share/defaults/hadoop/httpfs-site.xml
/usr/share/defaults/hadoop/kms-acls.xml
/usr/share/defaults/hadoop/kms-env.sh
/usr/share/defaults/hadoop/kms-log4j.properties
/usr/share/defaults/hadoop/kms-site.xml
/usr/share/defaults/hadoop/log4j.properties
/usr/share/defaults/hadoop/mapred-env.cmd
/usr/share/defaults/hadoop/mapred-env.sh
/usr/share/defaults/hadoop/mapred-queues.xml.template
/usr/share/defaults/hadoop/mapred-site.xml
/usr/share/defaults/hadoop/shellprofile.d/example.sh
/usr/share/defaults/hadoop/ssl-client.xml.example
/usr/share/defaults/hadoop/ssl-server.xml.example
/usr/share/defaults/hadoop/user_ec_policies.xml.template
/usr/share/defaults/hadoop/workers
/usr/share/defaults/hadoop/yarn-env.cmd
/usr/share/defaults/hadoop/yarn-env.sh
/usr/share/defaults/hadoop/yarn-site.xml
/usr/share/defaults/hadoop/yarnservice-log4j.properties
/usr/share/hadoop/client/hadoop-client-api-3.2.0.jar
/usr/share/hadoop/client/hadoop-client-minicluster-3.2.0.jar
/usr/share/hadoop/client/hadoop-client-runtime-3.2.0.jar
/usr/share/hadoop/common/hadoop-common-3.2.0-tests.jar
/usr/share/hadoop/common/hadoop-common-3.2.0.jar
/usr/share/hadoop/common/hadoop-kms-3.2.0.jar
/usr/share/hadoop/common/hadoop-nfs-3.2.0.jar
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.6.0.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.7.2.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.8.0.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.8.2.xml
/usr/share/hadoop/common/jdiff/Apache_Hadoop_Common_2.8.3.xml
/usr/share/hadoop/common/jdiff/Null.java
/usr/share/hadoop/common/jdiff/hadoop-core_0.20.0.xml
/usr/share/hadoop/common/jdiff/hadoop-core_0.21.0.xml
/usr/share/hadoop/common/jdiff/hadoop-core_0.22.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.17.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.2.xml
/usr/share/hadoop/common/jdiff/hadoop_0.18.3.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.19.2.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.0.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.1.xml
/usr/share/hadoop/common/jdiff/hadoop_0.20.2.xml
/usr/share/hadoop/common/lib/accessors-smart-1.2.jar
/usr/share/hadoop/common/lib/asm-5.0.4.jar
/usr/share/hadoop/common/lib/audience-annotations-0.5.0.jar
/usr/share/hadoop/common/lib/avro-1.7.7.jar
/usr/share/hadoop/common/lib/commons-beanutils-1.9.3.jar
/usr/share/hadoop/common/lib/commons-cli-1.2.jar
/usr/share/hadoop/common/lib/commons-codec-1.11.jar
/usr/share/hadoop/common/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/common/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/common/lib/commons-configuration2-2.1.1.jar
/usr/share/hadoop/common/lib/commons-io-2.5.jar
/usr/share/hadoop/common/lib/commons-lang3-3.7.jar
/usr/share/hadoop/common/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/common/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/common/lib/commons-net-3.6.jar
/usr/share/hadoop/common/lib/commons-text-1.4.jar
/usr/share/hadoop/common/lib/curator-client-2.12.0.jar
/usr/share/hadoop/common/lib/curator-framework-2.12.0.jar
/usr/share/hadoop/common/lib/curator-recipes-2.12.0.jar
/usr/share/hadoop/common/lib/dnsjava-2.1.7.jar
/usr/share/hadoop/common/lib/gson-2.2.4.jar
/usr/share/hadoop/common/lib/guava-19.0.jar
/usr/share/hadoop/common/lib/hadoop-annotations-3.2.0.jar
/usr/share/hadoop/common/lib/hadoop-auth-3.2.0.jar
/usr/share/hadoop/common/lib/htrace-core4-4.1.0-incubating.jar
/usr/share/hadoop/common/lib/httpclient-4.5.2.jar
/usr/share/hadoop/common/lib/httpcore-4.4.4.jar
/usr/share/hadoop/common/lib/jackson-annotations-2.9.5.jar
/usr/share/hadoop/common/lib/jackson-core-2.9.5.jar
/usr/share/hadoop/common/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/common/lib/jackson-databind-2.9.5.jar
/usr/share/hadoop/common/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/common/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/common/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/common/lib/javax.activation-api-1.2.0.jar
/usr/share/hadoop/common/lib/javax.servlet-api-3.1.0.jar
/usr/share/hadoop/common/lib/jaxb-api-2.2.11.jar
/usr/share/hadoop/common/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/common/lib/jcip-annotations-1.0-1.jar
/usr/share/hadoop/common/lib/jersey-core-1.19.jar
/usr/share/hadoop/common/lib/jersey-json-1.19.jar
/usr/share/hadoop/common/lib/jersey-server-1.19.jar
/usr/share/hadoop/common/lib/jersey-servlet-1.19.jar
/usr/share/hadoop/common/lib/jettison-1.1.jar
/usr/share/hadoop/common/lib/jetty-http-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-io-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-security-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-server-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-servlet-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-util-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-webapp-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jetty-xml-9.3.24.v20180605.jar
/usr/share/hadoop/common/lib/jsch-0.1.54.jar
/usr/share/hadoop/common/lib/json-smart-2.3.jar
/usr/share/hadoop/common/lib/jsp-api-2.1.jar
/usr/share/hadoop/common/lib/jsr305-3.0.0.jar
/usr/share/hadoop/common/lib/jsr311-api-1.1.1.jar
/usr/share/hadoop/common/lib/jul-to-slf4j-1.7.25.jar
/usr/share/hadoop/common/lib/kerb-admin-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-client-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-common-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-core-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-crypto-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-identity-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-server-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-simplekdc-1.0.1.jar
/usr/share/hadoop/common/lib/kerb-util-1.0.1.jar
/usr/share/hadoop/common/lib/kerby-asn1-1.0.1.jar
/usr/share/hadoop/common/lib/kerby-config-1.0.1.jar
/usr/share/hadoop/common/lib/kerby-pkix-1.0.1.jar
/usr/share/hadoop/common/lib/kerby-util-1.0.1.jar
/usr/share/hadoop/common/lib/kerby-xdr-1.0.1.jar
/usr/share/hadoop/common/lib/log4j-1.2.17.jar
/usr/share/hadoop/common/lib/metrics-core-3.2.4.jar
/usr/share/hadoop/common/lib/netty-3.10.5.Final.jar
/usr/share/hadoop/common/lib/nimbus-jose-jwt-4.41.1.jar
/usr/share/hadoop/common/lib/paranamer-2.3.jar
/usr/share/hadoop/common/lib/protobuf-java-3.6.1.jar
/usr/share/hadoop/common/lib/re2j-1.1.jar
/usr/share/hadoop/common/lib/slf4j-api-1.7.25.jar
/usr/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar
/usr/share/hadoop/common/lib/snappy-java-1.0.5.jar
/usr/share/hadoop/common/lib/stax2-api-3.1.4.jar
/usr/share/hadoop/common/lib/token-provider-1.0.1.jar
/usr/share/hadoop/common/lib/woodstox-core-5.0.3.jar
/usr/share/hadoop/common/lib/xz-1.0.jar
/usr/share/hadoop/common/lib/zookeeper-3.4.13.jar
/usr/share/hadoop/common/sources/hadoop-common-3.2.0-sources.jar
/usr/share/hadoop/common/sources/hadoop-common-3.2.0-test-sources.jar
/usr/share/hadoop/common/webapps/static/hadoop.css.gz
/usr/share/hadoop/hdfs/hadoop-hdfs-3.2.0-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-client-3.2.0-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-client-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-httpfs-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-native-client-3.2.0-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-native-client-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-nfs-3.2.0.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-rbf-3.2.0-tests.jar
/usr/share/hadoop/hdfs/hadoop-hdfs-rbf-3.2.0.jar
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.6.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.7.2.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.8.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.8.2.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.8.3.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_2.9.1.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0-alpha2.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0-alpha3.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0-alpha4.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.1.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.2.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.0.3.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.1.0.xml
/usr/share/hadoop/hdfs/jdiff/Apache_Hadoop_HDFS_3.1.1.xml
/usr/share/hadoop/hdfs/jdiff/Null.java
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.20.0.xml
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.21.0.xml
/usr/share/hadoop/hdfs/jdiff/hadoop-hdfs_0.22.0.xml
/usr/share/hadoop/hdfs/lib/accessors-smart-1.2.jar
/usr/share/hadoop/hdfs/lib/asm-5.0.4.jar
/usr/share/hadoop/hdfs/lib/audience-annotations-0.5.0.jar
/usr/share/hadoop/hdfs/lib/avro-1.7.7.jar
/usr/share/hadoop/hdfs/lib/commons-beanutils-1.9.3.jar
/usr/share/hadoop/hdfs/lib/commons-cli-1.2.jar
/usr/share/hadoop/hdfs/lib/commons-codec-1.11.jar
/usr/share/hadoop/hdfs/lib/commons-collections-3.2.2.jar
/usr/share/hadoop/hdfs/lib/commons-compress-1.4.1.jar
/usr/share/hadoop/hdfs/lib/commons-configuration2-2.1.1.jar
/usr/share/hadoop/hdfs/lib/commons-daemon-1.0.13.jar
/usr/share/hadoop/hdfs/lib/commons-io-2.5.jar
/usr/share/hadoop/hdfs/lib/commons-lang3-3.7.jar
/usr/share/hadoop/hdfs/lib/commons-logging-1.1.3.jar
/usr/share/hadoop/hdfs/lib/commons-math3-3.1.1.jar
/usr/share/hadoop/hdfs/lib/commons-net-3.6.jar
/usr/share/hadoop/hdfs/lib/commons-text-1.4.jar
/usr/share/hadoop/hdfs/lib/curator-client-2.12.0.jar
/usr/share/hadoop/hdfs/lib/curator-framework-2.12.0.jar
/usr/share/hadoop/hdfs/lib/curator-recipes-2.12.0.jar
/usr/share/hadoop/hdfs/lib/dnsjava-2.1.7.jar
/usr/share/hadoop/hdfs/lib/gson-2.2.4.jar
/usr/share/hadoop/hdfs/lib/guava-19.0.jar
/usr/share/hadoop/hdfs/lib/hadoop-annotations-3.2.0.jar
/usr/share/hadoop/hdfs/lib/hadoop-auth-3.2.0.jar
/usr/share/hadoop/hdfs/lib/htrace-core4-4.1.0-incubating.jar
/usr/share/hadoop/hdfs/lib/httpclient-4.5.2.jar
/usr/share/hadoop/hdfs/lib/httpcore-4.4.4.jar
/usr/share/hadoop/hdfs/lib/jackson-annotations-2.9.5.jar
/usr/share/hadoop/hdfs/lib/jackson-core-2.9.5.jar
/usr/share/hadoop/hdfs/lib/jackson-core-asl-1.9.13.jar
/usr/share/hadoop/hdfs/lib/jackson-databind-2.9.5.jar
/usr/share/hadoop/hdfs/lib/jackson-jaxrs-1.9.13.jar
/usr/share/hadoop/hdfs/lib/jackson-mapper-asl-1.9.13.jar
/usr/share/hadoop/hdfs/lib/jackson-xc-1.9.13.jar
/usr/share/hadoop/hdfs/lib/javax.activation-api-1.2.0.jar
/usr/share/hadoop/hdfs/lib/javax.servlet-api-3.1.0.jar
/usr/share/hadoop/hdfs/lib/jaxb-api-2.2.11.jar
/usr/share/hadoop/hdfs/lib/jaxb-impl-2.2.3-1.jar
/usr/share/hadoop/hdfs/lib/jcip-annotations-1.0-1.jar
/usr/share/hadoop/hdfs/lib/jersey-core-1.19.jar
/usr/share/hadoop/hdfs/lib/jersey-json-1.19.jar
/usr/share/hadoop/hdfs/lib/jersey-server-1.19.jar
/usr/share/hadoop/hdfs/lib/jersey-servlet-1.19.jar
/usr/share/hadoop/hdfs/lib/jettison-1.1.jar
/usr/share/hadoop/hdfs/lib/jetty-http-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-io-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-security-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-server-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-servlet-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-util-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-util-ajax-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-webapp-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jetty-xml-9.3.24.v20180605.jar
/usr/share/hadoop/hdfs/lib/jsch-0.1.54.jar
/usr/share/hadoop/hdfs/lib/json-simple-1.1.1.jar
/usr/share/hadoop/hdfs/lib/json-smart-2.3.jar
/usr/share/hadoop/hdfs/lib/jsr305-3.0.0.jar
/usr/share/hadoop/hdfs/lib/jsr311-api-1.1.1.jar
/usr/share/hadoop/hdfs/lib/kerb-admin-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-client-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-common-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-core-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-crypto-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-identity-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-server-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-simplekdc-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerb-util-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerby-asn1-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerby-config-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerby-pkix-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerby-util-1.0.1.jar
/usr/share/hadoop/hdfs/lib/kerby-xdr-1.0.1.jar
/usr/share/hadoop/hdfs/lib/leveldbjni-all-1.8.jar
/usr/share/hadoop/hdfs/lib/log4j-1.2.17.jar
/usr/share/hadoop/hdfs/lib/netty-3.10.5.Final.jar
/usr/share/hadoop/hdfs/lib/netty-all-4.0.52.Final.jar
/usr/share/hadoop/hdfs/lib/nimbus-jose-jwt-4.41.1.jar
/usr/share/hadoop/hdfs/lib/okhttp-2.7.5.jar
/usr/share/hadoop/hdfs/lib/okio-1.6.0.jar
/usr/share/hadoop/hdfs/lib/paranamer-2.3.jar
/usr/share/hadoop/hdfs/lib/protobuf-java-3.6.1.jar
/usr/share/hadoop/hdfs/lib/re2j-1.1.jar
/usr/share/hadoop/hdfs/lib/snappy-java-1.0.5.jar
/usr/share/hadoop/hdfs/lib/stax2-api-3.1.4.jar
/usr/share/hadoop/hdfs/lib/token-provider-1.0.1.jar
/usr/share/hadoop/hdfs/lib/woodstox-core-5.0.3.jar
/usr/share/hadoop/hdfs/lib/xz-1.0.jar
/usr/share/hadoop/hdfs/lib/zookeeper-3.4.13.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-3.2.0-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-client-3.2.0-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-client-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-native-client-3.2.0-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-native-client-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-rbf-3.2.0-sources.jar
/usr/share/hadoop/hdfs/sources/hadoop-hdfs-rbf-3.2.0-test-sources.jar
/usr/share/hadoop/hdfs/webapps/datanode/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/datanode/datanode.html
/usr/share/hadoop/hdfs/webapps/datanode/dn.js
/usr/share/hadoop/hdfs/webapps/datanode/index.html
/usr/share/hadoop/hdfs/webapps/datanode/robots.txt
/usr/share/hadoop/hdfs/webapps/hdfs/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/hdfs/dfshealth.html
/usr/share/hadoop/hdfs/webapps/hdfs/dfshealth.js
/usr/share/hadoop/hdfs/webapps/hdfs/explorer.html
/usr/share/hadoop/hdfs/webapps/hdfs/explorer.js
/usr/share/hadoop/hdfs/webapps/hdfs/index.html
/usr/share/hadoop/hdfs/webapps/hdfs/robots.txt
/usr/share/hadoop/hdfs/webapps/journal/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/journal/index.html
/usr/share/hadoop/hdfs/webapps/journal/robots.txt
/usr/share/hadoop/hdfs/webapps/nfs3/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/router/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/router/federationhealth.html
/usr/share/hadoop/hdfs/webapps/router/federationhealth.js
/usr/share/hadoop/hdfs/webapps/router/index.html
/usr/share/hadoop/hdfs/webapps/router/robots.txt
/usr/share/hadoop/hdfs/webapps/secondary/WEB-INF/web.xml
/usr/share/hadoop/hdfs/webapps/secondary/index.html
/usr/share/hadoop/hdfs/webapps/secondary/robots.txt
/usr/share/hadoop/hdfs/webapps/secondary/snn.js
/usr/share/hadoop/hdfs/webapps/secondary/status.html
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-editable.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-editable.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.min.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.min.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap-theme.min.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.min.css
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.min.css.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/css/bootstrap.min.css.map
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.eot
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.svg
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.ttf
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff2
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap-editable.min.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap-editable.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.js.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.min.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/bootstrap.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/npm.js
/usr/share/hadoop/hdfs/webapps/static/bootstrap-3.3.7/js/npm.js.gz
/usr/share/hadoop/hdfs/webapps/static/d3-v4.1.1.min.js
/usr/share/hadoop/hdfs/webapps/static/d3-v4.1.1.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.css
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.css.gz
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.js
/usr/share/hadoop/hdfs/webapps/static/dataTables.bootstrap.js.gz
/usr/share/hadoop/hdfs/webapps/static/dfs-dust.js
/usr/share/hadoop/hdfs/webapps/static/dfs-dust.js.gz
/usr/share/hadoop/hdfs/webapps/static/dust-full-2.0.0.min.js
/usr/share/hadoop/hdfs/webapps/static/dust-full-2.0.0.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/dust-helpers-1.1.1.min.js
/usr/share/hadoop/hdfs/webapps/static/dust-helpers-1.1.1.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/hadoop.css
/usr/share/hadoop/hdfs/webapps/static/hadoop.css.gz
/usr/share/hadoop/hdfs/webapps/static/jquery-3.3.1.min.js
/usr/share/hadoop/hdfs/webapps/static/jquery-3.3.1.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/jquery.dataTables.min.js
/usr/share/hadoop/hdfs/webapps/static/jquery.dataTables.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/json-bignum.js
/usr/share/hadoop/hdfs/webapps/static/json-bignum.js.gz
/usr/share/hadoop/hdfs/webapps/static/moment.min.js
/usr/share/hadoop/hdfs/webapps/static/moment.min.js.gz
/usr/share/hadoop/hdfs/webapps/static/rbf.css
/usr/share/hadoop/hdfs/webapps/static/rest-csrf.js
/usr/share/hadoop/hdfs/webapps/static/rest-csrf.js.gz
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-app-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-common-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-core-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-plugins-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-3.2.0-tests.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-nativetask-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-shuffle-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-client-uploader-3.2.0.jar
/usr/share/hadoop/mapreduce/hadoop-mapreduce-examples-3.2.0.jar
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.6.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.7.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.8.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.8.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_2.8.3.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Common_3.1.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.6.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.7.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.8.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.8.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_2.8.3.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_Core_3.1.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.6.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.7.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.8.0.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.8.2.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_2.8.3.xml
/usr/share/hadoop/mapreduce/jdiff/Apache_Hadoop_MapReduce_JobClient_3.1.0.xml
/usr/share/hadoop/mapreduce/jdiff/Null.java
/usr/share/hadoop/mapreduce/lib-examples/hsqldb-2.3.4.jar
/usr/share/hadoop/mapreduce/lib/hamcrest-core-1.3.jar
/usr/share/hadoop/mapreduce/lib/junit-4.11.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-app-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-app-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-common-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-common-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-core-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-core-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-plugins-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-hs-plugins-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-jobclient-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-jobclient-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-nativetask-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-nativetask-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-shuffle-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-client-shuffle-3.2.0-test-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-examples-3.2.0-sources.jar
/usr/share/hadoop/mapreduce/sources/hadoop-mapreduce-examples-3.2.0-test-sources.jar
/usr/share/hadoop/tools/lib/aliyun-sdk-oss-2.8.3.jar
/usr/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.375.jar
/usr/share/hadoop/tools/lib/azure-data-lake-store-sdk-2.2.9.jar
/usr/share/hadoop/tools/lib/azure-keyvault-core-1.0.0.jar
/usr/share/hadoop/tools/lib/azure-storage-7.0.0.jar
/usr/share/hadoop/tools/lib/hadoop-aliyun-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-archive-logs-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-archives-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-aws-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-azure-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-azure-datalake-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-datajoin-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-distcp-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-extras-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-fs2img-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-gridmix-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-kafka-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-openstack-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-resourceestimator-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-rumen-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-sls-3.2.0.jar
/usr/share/hadoop/tools/lib/hadoop-streaming-3.2.0.jar
/usr/share/hadoop/tools/lib/jdom-1.1.jar
/usr/share/hadoop/tools/lib/kafka-clients-0.8.2.1.jar
/usr/share/hadoop/tools/lib/lz4-1.2.0.jar
/usr/share/hadoop/tools/lib/ojalgo-43.0.jar
/usr/share/hadoop/tools/lib/wildfly-openssl-1.0.4.Final.jar
/usr/share/hadoop/tools/resourceestimator/bin/estimator.cmd
/usr/share/hadoop/tools/resourceestimator/bin/estimator.sh
/usr/share/hadoop/tools/resourceestimator/bin/start-estimator.cmd
/usr/share/hadoop/tools/resourceestimator/bin/start-estimator.sh
/usr/share/hadoop/tools/resourceestimator/bin/stop-estimator.cmd
/usr/share/hadoop/tools/resourceestimator/bin/stop-estimator.sh
/usr/share/hadoop/tools/resourceestimator/conf/resourceestimator-config.xml
/usr/share/hadoop/tools/resourceestimator/data/resourceEstimatorService.txt
/usr/share/hadoop/tools/sls/bin/rumen2sls.sh
/usr/share/hadoop/tools/sls/bin/slsrun.sh
/usr/share/hadoop/tools/sls/html/css/bootstrap-responsive.min.css
/usr/share/hadoop/tools/sls/html/css/bootstrap.min.css
/usr/share/hadoop/tools/sls/html/js/thirdparty/bootstrap.min.js
/usr/share/hadoop/tools/sls/html/js/thirdparty/d3-LICENSE
/usr/share/hadoop/tools/sls/html/js/thirdparty/d3.v3.js
/usr/share/hadoop/tools/sls/html/js/thirdparty/jquery.js
/usr/share/hadoop/tools/sls/html/showSimulationTrace.html
/usr/share/hadoop/tools/sls/html/simulate.html.template
/usr/share/hadoop/tools/sls/html/simulate.info.html.template
/usr/share/hadoop/tools/sls/html/track.html.template
/usr/share/hadoop/tools/sls/sample-conf/capacity-scheduler.xml
/usr/share/hadoop/tools/sls/sample-conf/fair-scheduler.xml
/usr/share/hadoop/tools/sls/sample-conf/log4j.properties
/usr/share/hadoop/tools/sls/sample-conf/sls-runner.xml
/usr/share/hadoop/tools/sls/sample-conf/yarn-site.xml
/usr/share/hadoop/tools/sls/sample-data/2jobs2min-rumen-jh.json
/usr/share/hadoop/tools/sources/hadoop-archive-logs-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archive-logs-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archives-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-archives-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-datajoin-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-datajoin-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-distcp-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-distcp-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-extras-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-extras-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-gridmix-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-gridmix-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-resourceestimator-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-resourceestimator-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-rumen-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-rumen-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-sls-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-sls-3.2.0-test-sources.jar
/usr/share/hadoop/tools/sources/hadoop-streaming-3.2.0-sources.jar
/usr/share/hadoop/tools/sources/hadoop-streaming-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/hadoop-yarn-api-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-applications-distributedshell-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-applications-unmanaged-am-launcher-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-client-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-common-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-registry-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-applicationhistoryservice-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-common-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-nodemanager-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-resourcemanager-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-router-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-sharedcachemanager-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-tests-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-timeline-pluginstorage-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-server-web-proxy-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-services-api-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-services-core-3.2.0.jar
/usr/share/hadoop/yarn/hadoop-yarn-submarine-3.2.0.jar
/usr/share/hadoop/yarn/lib/HikariCP-java7-2.4.12.jar
/usr/share/hadoop/yarn/lib/aopalliance-1.0.jar
/usr/share/hadoop/yarn/lib/ehcache-3.3.1.jar
/usr/share/hadoop/yarn/lib/fst-2.50.jar
/usr/share/hadoop/yarn/lib/geronimo-jcache_1.0_spec-1.0-alpha-1.jar
/usr/share/hadoop/yarn/lib/guice-4.0.jar
/usr/share/hadoop/yarn/lib/guice-servlet-4.0.jar
/usr/share/hadoop/yarn/lib/jackson-jaxrs-base-2.9.5.jar
/usr/share/hadoop/yarn/lib/jackson-jaxrs-json-provider-2.9.5.jar
/usr/share/hadoop/yarn/lib/jackson-module-jaxb-annotations-2.9.5.jar
/usr/share/hadoop/yarn/lib/java-util-1.9.0.jar
/usr/share/hadoop/yarn/lib/javax.inject-1.jar
/usr/share/hadoop/yarn/lib/jersey-client-1.19.jar
/usr/share/hadoop/yarn/lib/jersey-guice-1.19.jar
/usr/share/hadoop/yarn/lib/json-io-2.5.1.jar
/usr/share/hadoop/yarn/lib/metrics-core-3.2.4.jar
/usr/share/hadoop/yarn/lib/mssql-jdbc-6.2.1.jre7.jar
/usr/share/hadoop/yarn/lib/objenesis-1.0.jar
/usr/share/hadoop/yarn/lib/snakeyaml-1.16.jar
/usr/share/hadoop/yarn/lib/swagger-annotations-1.5.4.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-api-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-api-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-distributedshell-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-distributedshell-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-unmanaged-am-launcher-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-applications-unmanaged-am-launcher-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-client-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-client-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-common-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-common-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-applicationhistoryservice-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-applicationhistoryservice-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-common-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-common-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-nodemanager-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-nodemanager-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-resourcemanager-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-resourcemanager-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-tests-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-tests-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-web-proxy-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-server-web-proxy-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-api-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-api-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-core-3.2.0-sources.jar
/usr/share/hadoop/yarn/sources/hadoop-yarn-services-core-3.2.0-test-sources.jar
/usr/share/hadoop/yarn/test/hadoop-yarn-server-tests-3.2.0-tests.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-hbase-client-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-hbase-common-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/hadoop-yarn-server-timelineservice-hbase-coprocessor-3.2.0.jar
/usr/share/hadoop/yarn/timelineservice/lib/commons-csv-1.0.jar
/usr/share/hadoop/yarn/timelineservice/lib/commons-lang-2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-annotations-1.2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-client-1.2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-common-1.2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/hbase-protocol-1.2.6.jar
/usr/share/hadoop/yarn/timelineservice/lib/htrace-core-3.1.0-incubating.jar
/usr/share/hadoop/yarn/timelineservice/lib/jcodings-1.0.13.jar
/usr/share/hadoop/yarn/timelineservice/lib/joni-2.1.2.jar
/usr/share/hadoop/yarn/timelineservice/lib/metrics-core-2.2.0.jar
/usr/share/hadoop/yarn/timelineservice/test/hadoop-yarn-server-timelineservice-hbase-tests-3.2.0.jar
/usr/share/hadoop/yarn/yarn-service-examples/httpd-no-dns/httpd-no-dns.json
/usr/share/hadoop/yarn/yarn-service-examples/httpd-no-dns/httpd-proxy-no-dns.conf
/usr/share/hadoop/yarn/yarn-service-examples/httpd/httpd-proxy.conf
/usr/share/hadoop/yarn/yarn-service-examples/httpd/httpd.json
/usr/share/hadoop/yarn/yarn-service-examples/sleeper/sleeper.json

%files dev
%defattr(-,root,root,-)
/usr/include/Pipes.hh
/usr/include/SerialUtils.hh
/usr/include/StringUtils.hh
/usr/include/TemplateFactory.hh
/usr/include/hdfs.h

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/hadoop/LICENSE.txt
/usr/share/doc/hadoop/NOTICE.txt
/usr/share/doc/hadoop/README.txt

%files lib
%defattr(-,root,root,-)
/usr/lib/native/libhadoop.so
/usr/lib/native/libhadoop.so.1.0.0
/usr/lib/native/libnativetask.so
/usr/lib/native/libnativetask.so.1.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/hadoop-config.cmd
/usr/libexec/hadoop-config.sh
/usr/libexec/hadoop-functions.sh
/usr/libexec/hadoop-layout.sh.example
/usr/libexec/hdfs-config.cmd
/usr/libexec/hdfs-config.sh
/usr/libexec/mapred-config.cmd
/usr/libexec/mapred-config.sh
/usr/libexec/shellprofile.d/hadoop-aliyun.sh
/usr/libexec/shellprofile.d/hadoop-archive-logs.sh
/usr/libexec/shellprofile.d/hadoop-archives.sh
/usr/libexec/shellprofile.d/hadoop-aws.sh
/usr/libexec/shellprofile.d/hadoop-azure-datalake.sh
/usr/libexec/shellprofile.d/hadoop-azure.sh
/usr/libexec/shellprofile.d/hadoop-distcp.sh
/usr/libexec/shellprofile.d/hadoop-extras.sh
/usr/libexec/shellprofile.d/hadoop-gridmix.sh
/usr/libexec/shellprofile.d/hadoop-hdfs.sh
/usr/libexec/shellprofile.d/hadoop-httpfs.sh
/usr/libexec/shellprofile.d/hadoop-kafka.sh
/usr/libexec/shellprofile.d/hadoop-kms.sh
/usr/libexec/shellprofile.d/hadoop-mapreduce.sh
/usr/libexec/shellprofile.d/hadoop-openstack.sh
/usr/libexec/shellprofile.d/hadoop-rumen.sh
/usr/libexec/shellprofile.d/hadoop-s3guard.sh
/usr/libexec/shellprofile.d/hadoop-streaming.sh
/usr/libexec/shellprofile.d/hadoop-yarn.sh
/usr/libexec/tools/hadoop-archive-logs.sh
/usr/libexec/tools/hadoop-archives.sh
/usr/libexec/tools/hadoop-aws.sh
/usr/libexec/tools/hadoop-distcp.sh
/usr/libexec/tools/hadoop-extras.sh
/usr/libexec/tools/hadoop-gridmix.sh
/usr/libexec/tools/hadoop-resourceestimator.sh
/usr/libexec/tools/hadoop-rumen.sh
/usr/libexec/tools/hadoop-sls.sh
/usr/libexec/tools/hadoop-streaming.sh
/usr/libexec/yarn-config.cmd
/usr/libexec/yarn-config.sh
